Blog Post: Alpha Testing the Lesson Infrastructure Redesign
carpentries/carpentries.org-archive pull request #1105
Opened 2021-06-21 18:58 UTC by zkamvar

2021-06-25 00:11 UTC, zkamvar commented
@fmichonneau, @tobyhodges, @ErinBecker, @kmomar, can you take a gander at this abomination?

2021-06-25 08:15 UTC, fmichonneau reviewed
Great work on this post. It captures nicely the effort that went into the testing and summarizes the findings clearly.

A few typos and some editorial suggestions that you are free to ignore.

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Alpha testing is a 'bare bones' testing where participants complete a set of tasks with functional, but not fully-featured product.
```suggestion
During our alpha testing, participants complete a set of tasks with functional, but not fully-featured products.
```

I'm not sure our definition of alpha testing is universal, and removed duplication between "bare bone" and "not fully-featured".

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +The participants in the tests are given a set of pre-defined tasks to accomplish and asked about how they felt about their experiences vs. what their expectations.
```suggestion
The participants in the tests are given a set of pre-defined tasks to accomplish and asked about how they felt about their experiences vs. their expectations.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +These tests are designed identify common stumbling blocks and any unforseen difficulties that arise from user experiences by reducing the feature space to the core functionality.
```suggestion
These tests are designed to identify common stumbling blocks and any unforeseen difficulties that arise when users test the core functionality of a product.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +> ...the pandoc looked more confusing, but when I read about what it requires it's less specific and so the eaisest.
```suggestion
> ...the pandoc looked more confusing, but when I read about what it requires it's less specific and so the easiest.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +This includes maintainers, instructors, core team members, incubator maintainers, and even people who were brand new to The Carpentries.
```suggestion
This included Maintainers, Instructors, Core Team members, Incubator Maintainers, and even people who were brand new to The Carpentries.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +1. Is the infrastructure [installable?](https://github.com/carpentries/sandpaper-docs/issues/33)
```suggestion
1. Is the infrastructure [installable](https://github.com/carpentries/sandpaper-docs/issues/33)?
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +2. Can participants [create a lesson?](https://tang0008.github.io/buoyant-barnacle/)
```suggestion
2. Can participants [create a lesson](https://tang0008.github.io/buoyant-barnacle/)?
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +3. Can participants [contribute to a lesson?](https://github.com/carpentries/sandpaper-docs/pull/34)
```suggestion
3. Can participants [contribute to a lesson](https://github.com/carpentries/sandpaper-docs/pull/34)?
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +> This is an ongoing series of blog posts about the next iteration of the Lesson Infrastructure.
```suggestion
> This is an ongoing series of blog posts about the next iteration of the [Lesson Infrastructure]({{ site.url }}/posts-by-tags/#lesson-infrastructure).
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +As our community has grown, it became evident that our infrastructure would not easily scale as lessons would rapidly fall out-of-date with the current toolchains and styling.
```suggestion
As our community has grown, it became evident that our current lesson infrastructure would not scale as updates to the toolchains and styling continues to involve complex manual steps. 
```

as an attempt to clarify why the lessons would fall out of date.

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Of course, [as we have learned from previous iterations of the lesson template][previous-iteration], if we create something that does not work for the community, it is useless.
```suggestion
Of course, [as we have learned from previous iterations of the lesson template][previous-iteration], we need to create something that works *for the community*.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +After investigating several options from our lesson infrastructure, we realized that the [R publishing ecosystem][rmd] aligned best with our values because it has friendly communities, is available a
```suggestion
After investigating several options for our lesson infrastructure, we realized that the [R publishing ecosystem][rmd] aligned best with our values because it has friendly communities, is available as a binary application on all operating systems, and allows us to integrate with all the features we currently offer. 
```
not sure?

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +After investigating several options from our lesson infrastructure, we realized that the [R publishing ecosystem][rmd] aligned best with our values because it has friendly communities, is available a
```suggestion
After investigating several options from our lesson infrastructure, we realized that the [R publishing ecosystem][rmd] aligned best with our values because it has friendly communities, is open source, easy to install on all operating systems, and allows us to integrate with all the features we currently offer. 
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +This post describes our efforts to test changes coming to [callout blocks][bq] and the overall infrastructure.
```suggestion
This post describes our initial efforts to test changes coming to [callout blocks][bq] and the overall lesson infrastructure.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +In this way, we could be sure that the solutions we come up with were stable before spending time adding extra features that depend on the base design.
```suggestion
With this approach, we could test that the solutions we come up with were intuitive before spending time adding extra features.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +To get to this solution, we recurited maintainers for anonymous testing and proposed three potential solutions for this syntax using one of three alternatives:
```suggestion
To get to this solution, we recruited Maintainers for anonymous testing and proposed three potential solutions for this syntax using one of three alternatives:
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +[Pandoc section fence syntax][en-garde] won the challenge because it was reported to be the easiest to use (6/11) and [participants made the fewest syntax errors][results][^1] when they were asked to
```suggestion
We selected the [Pandoc section fence syntax][en-garde] because testers reported it was the easiest to use (6/11) and [they made the fewest syntax errors][results][^1] when they were asked to [reproduce a challenge/solution block in that syntax without rendering the result to HTML][challenge].
```
use of the word "challenge" here might introduce confusion as we are talking about the challenge syntax.

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +### Infrastructure Testing
```suggestion
### Lesson Infrastructure Testing
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +1. Tell me about the first time you used the Carpentries Lesson Template (styles repo).
```suggestion
1. Tell me about the first time you used the current Carpentries Lesson Template (our [styles](https://github.com/carpentries/styles) repo).
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +As our community has grown, it became evident that our infrastructure would not easily scale as lessons would rapidly fall out-of-date with the current toolchains and styling.
Maybe also add a sentence about how when the previous iteration of the lesson template was created, only a few people needed to be able to render the lesson locally, but now we have 100s of people doing lesson development with our lesson template.

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +On two ends of the spectrum, there were people who only wanted the quickstart to those who needed documentation for how the machinery was working so that they could confirm it was not being held toge
"peanut butter and paperclips" might be a colloquialism that is difficult to understand for non-native speakers.

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +One way to achieve this is to write the quickstart documentation and then invtie people to read the "nerd's documentation" if they were curious.
```suggestion
One way to achieve this is to write the quickstart documentation and then invite people to read a more in-depth documentation if they were curious.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +This way, people who only want to get the task done can skip that information guilt free.
```suggestion
This way, people who only want to get the task done can skip that information.
```

2021-06-25 08:15 UTC, fmichonneau commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +We will be updating documentation, fixing bugs, and enhancing the deployment pipelines.
```suggestion
In the meantime, we will be updating documentation, fixing bugs, and enhancing the deployment pipelines. 
```

2021-06-25 14:20 UTC, zkamvar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +> This is an ongoing series of blog posts about the next iteration of the Lesson Infrastructure.
:100:

2021-06-25 14:29 UTC, zkamvar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +On two ends of the spectrum, there were people who only wanted the quickstart to those who needed documentation for how the machinery was working so that they could confirm it was not being held toge
Agreed. This was exhausted Zhian speaking. I'll think of something better to write here or just get rid of it all together given that this has turned into a looooooong post

2021-06-25 14:47 UTC, zkamvar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +As our community has grown, it became evident that our infrastructure would not easily scale as lessons would rapidly fall out-of-date with the current toolchains and styling.
Agreed. I will address this in my next commit.

2021-06-25 18:34 UTC, kmomar commented
@zkamvar Content-wise looks good! I'm going to scan for contractions, typos, and readability and then we should be good to go!

2021-06-25 19:11 UTC, kmomar requested changes

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +As our community has grown in the past few years, it became evident that our current lesson infrastructure---where implementing updates involves complex manual steps---would not scale well.
```suggestion
As our community has grown in the past few years, it has become evident that our current lesson infrastructure---where implementing updates involves complex manual steps---does not scale well.
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +We now have more than 100 official and community-developed lessons combined and it's clear that the ability to install and keep the infrastructure up-to-date on one's machine is a rare trait.
```suggestion
We now have more than 100 official and community-developed lessons combined.
Based on the feedback from our much larger maintainer community, it is clear that many find it challenging to keep the infrastructure up-to-date on their own machines.
```
Not sure how to change it to keep meaning, but can we remove "it is clear" and "rare trait." to improve readability and accessibility

Edit: Zhian---I've tried to incorporate my changes here that make it a bit easier to digest.

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +The incubator comprises of more than one half of all lessons in the current day.'
```suggestion
The incubator comprises more than one half of all lessons in the current day.' 
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +The growth in the number of lessons has drastically increased between December 2014 to June 2021.
```suggestion
The growth in the number of lessons has drastically increased between December 2014 and June 2021. 
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Thus, We proposed [design principles of the next iteration of the lesson template][depr] to guide us in making lesson contribution a better experience for all involved.
```suggestion
Thus, We proposed the following [design principles of the next iteration of the lesson template][depr] to guide us in making lesson contribution a better experience for all involved.
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +With this approach, we could test that the solutions we come up with were intuitive before spending time adding extra features.
```suggestion
With this approach, we can test that the solutions we come up with are intuitive before spending time adding extra features.
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +This included Maintainers, Instructors, Core Team members, Incubator Maintainers, and even people who were brand new to The Carpentries.
```suggestion
This included Maintainers, Instructors, Core Team members, Incubator Maintainers, and people who were brand new to The Carpentries.
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Our goal for testing  was to assess three salient aspects:
```suggestion
Our goal for testing was to assess three salient aspects:
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +These volunteers represented people who were brand new to The Carpentries, active community members who have been helping to create a welcoming community for years, and everyone in between.
```suggestion
These volunteers represented people who were brand new to The Carpentries, active community members who have been helping to create a welcoming community for years, and others involved in The Carpentries.
```

changed "everyone in between" as it could be read that there were active community members who WEREN'T helping create a welcoming community

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +The next most frequent problems were coming from connecting to GitHub and even from [the Git installation itself][git-problems].
```suggestion
The next most frequent problems came from connecting to GitHub and even from [the Git installation itself][git-problems].
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Overall, the experience from the participants was largely positive.
```suggestion
Overall, the feedback from the participants about their experience was largely positive.
```

2021-06-25 19:11 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Here's the thing about updates, though: they can be utterly terrifying[^3].
```suggestion
Here is the thing about updates, though: they can be utterly terrifying[^3].
```

2021-06-25 22:55 UTC, ErinBecker commented
Woo hooo @zkamvar! I'm happy to roll out with the feedback from @kmomar and @fmichonneau.

2021-07-06 16:18 UTC, zkamvar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Thus, We proposed [design principles of the next iteration of the lesson template][depr] to guide us in making lesson contribution a better experience for all involved.
I think "the following" is misleading here because it suggests that the deign principles are outlined in this post.

2021-07-06 16:19 UTC, zkamvar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Our goal for testing  was to assess three salient aspects:
I see you are from the newer generation who doesn't follow the "two spaces after an 'ing' rule" :stuck_out_tongue_closed_eyes:

2021-07-06 16:20 UTC, zkamvar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +These volunteers represented people who were brand new to The Carpentries, active community members who have been helping to create a welcoming community for years, and everyone in between.
oof good catch!

2021-07-06 18:14 UTC, kmomar commented on _posts/2021/07/2021-07-06-infrastructure-testing.md
> +Thus, We proposed [design principles of the next iteration of the lesson template][depr] to guide us in making lesson contribution a better experience for all involved.
That is a very good point. I misunderstood what the link was referring to. I think we can proceed without this edit.

2021-07-06 18:14 UTC, kmomar approved these changes

2021-07-06 19:44 UTC, merged