Create 2021-09-21-incubator-lesson-data-visualization-python.md
carpentries/carpentries.org-archive pull request #1164
Opened 2021-09-20 17:27 UTC by kmomar

2021-09-21 16:37 UTC, kmomar commented
Please Review: @jenna-jordan

2021-09-24 16:11 UTC, MCMaurer commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +[lesson-pages]: <lesson URL from form>
Whoops, I forgot to add the lesson URL here. Should be https://carpentries-incubator.github.io/python-interactive-data-visualizations/

2021-09-25 01:56 UTC, jenna-jordan requested changes

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +1. How to wrangle data into the right format for creating visualizations using the pandas library (and about Tidy Data)
1. Learn how to wrangle data into a tidy format using the pandas library.

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +2. How to create some basic visualizations using the Plotly Express library
2. Learn how to create some basic visualizations using the Plotly Express library.

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +3. How to create a web app for interacting with the visualizations using the Streamlit library
3. Learn how to create a web app using the Streamlit library for sharing the visualizations, as well as interacting with the data and visualizations via widgets.

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +Learners who have recently completed the "Plotting and Programming in Python" lesson (or have some experience with Python and pandas) and want to learn more about data visualizations - and building i
This workshop is appropriate for learners who have recently completed the "Plotting and Programming in Python" lesson (or have some experience with Python and pandas), and  is targeted specifically to those who want to learn more about creating data visualizations and building interactive dashboards. The lesson can be taught in 1 hour (if you skip the exercises and include Episode 1 in the prep) or up to 2 hours (if you include time for students to work through all the exercises and include Episode 1 in the workshop time).

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +The lesson is in a finished state - all of the lessons are written and there are exercises included. I have taught the lesson once earlier in its development. It's now ready to be taught by other ins
The lesson is currently in "Alpha" stage - all of the episodes are written, there are exercises included, and there are instructor notes that may be helpful on that extras page. I have taught the lesson once earlier in its development. It is now ready to be taught by other instructors (but has not yet been taught by other instructors), and I am looking forward to everyone's feedback on the lesson.

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +I would like for other instructors to teach the lesson and provide feedback on the experience, especially as regards pacing, clarity, and points where learners struggled.
I would love for other instructors to teach the lesson and provide feedback on the experience, especially as regards pacing, clarity, and points where learners struggled. I'd also welcome feedback from anyone willing to simply look the lesson over!

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +To contact me directly regarding questions, email me at jenna.jrdn@gmail.com. If there's a problem with the lesson, then submit an issue to the GitHub repo.
To contact me directly regarding questions about the lesson, you can email me at jenna.jrdn@gmail.com. You can also reach me on Twitter, at [@JennaJrdn](https://twitter.com/JennaJrdn). If there is a problem with the lesson, or you have a suggestion for improvement, then please submit an issue to the GitHub repo!

2021-09-25 01:56 UTC, jenna-jordan commented on _posts/2021/09/2021-09-21-incubator-lesson-data-visualization-python.md
> +teaser: "Get involved in the community’s development of a new lesson on the development of interactive data visualizations in Python."
teaser: "Get involved in the community’s development of a new lesson on how to create interactive data visualizations in Python."

2021-09-28 14:57 UTC, merged