Carpentries Workbench
carpentries/carpentries.org-archive pull request #1308
Opened 2022-01-27 17:44 UTC by zkamvar

Still working on this one. You will want to squash and merge when all is said and done.

2022-01-28 10:34 UTC, tobyhodges requested changes
This is so exciting @zkamvar! I really enjoyed reading through it, and have made a few suggestions and typo fixes. I had a stab at the call for volunteers.

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +our lesson infrastructure as the repoirtoir of our lesson developers continues
```suggestion
our lesson infrastructure as the repertoire of our lesson developers continues
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +Because we deeply understand the implications of changing things too rapidly,
```suggestion
Because these are large changes with far-reaching consequences for our community,
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +infrastructure in how you work (either teaching, authoring, or maintianing)**
```suggestion
instructors. **If you would like to begin exploring The Carpentries Workbench
and help us out with beta testing, please get in touch CONTACT INFO HERE.**
It is vital that we include a wide range of perspectives in this process.
We would like to learn from your experience with the new infrastructure 
however you work with our lesson sites: 
whether that is teaching the lesson in a workshop, 
developing a new lesson, 
or maintaining an existing repository.
Similarly, we are keen to include you regardless of your familiarity with the infrastructure on which our
lessons are currently based: 
regardless of whether you are new to The Carpentries community or 
have been working with our lesson sites for many years,
we want you to get involved.
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +there may be a few rendering errors]. This is what the 'Making Choices' episode
```suggestion
there may be a few rendering errors - please open an issue on the repository if you find any]. This is what the 'Making Choices' episode
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +</figure>
Can you use a screencapture that includes the equivalent content to that shown in the previous figure? E.g. I would like to be able to see the code blocks that are included in the _styles_ screengrab.

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +### For Instructors: Instructor Notes
```suggestion
### For Instructors: Instructor View
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +TeSS](https://tess.elixir-europe.org/), which will give more exposure to the
```suggestion
lessons so that they can be indexed and aggregated on repositories such as [ELIXIR's Training Portal, 
TeSS](https://tess.elixir-europe.org/), which will increase the lessons' reach and give more exposure to the
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +One of the things I'm really excited about with the lesson infrastructure is a
```suggestion
One of the things we're really excited about with the lesson infrastructure is a
```

you were using "we" for most of the post up to now - recommend to stick with it unless it's you are really only talking about yourself (like with the aside about impatience, above)

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +
```suggestion
request previews][pr-preview] that will avoid lessons suddenly breaking when
new package versions are released.

```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +As I mentioned earlier, we will not make this transition all at once. There are
```suggestion
As mentioned earlier, we will not make this transition all at once. There are
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +one final lesson release and then slowly migrate the lessons based on an opt-in
```suggestion
one more lesson release and then slowly migrate the lessons based on an opt-in
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +process by the maintainers and the instructors will be notified at least two
```suggestion
process by the maintainers. Instructors will be notified at least two
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +weeks in advance of the migration.
```suggestion
weeks in advance of these migrations. 
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +specific commits).
```suggestion
For the maintainers, we have set up [a workflow for automated conversion with
customisation](https://github.com/data-lessons/lesson-transition/), and once
the maintainers/authors of the lesson are ready and they consent, we will
transition the lesson, preserving the commit history (stripping the styles-
specific commits). 
```

I feel bad about this one, because it really has been all your work and maybe using "we" dilutes the respect you have earned. Feel free to reject this suggestion.

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +developers towards the pit of success in terms of creating accessible and
"pit of success" was a new phrase for me, and may not be easy from an i18n perspective - could you link to a resource where someone could understand better what you mean?

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +up-to-date lessons in any lanuguge (both human and computer).
```suggestion
up-to-date lessons in any language (both human and computer).
```

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +OMAR PLEASE HELP THING OF A GOOD ENDING
You should definitely repeat the call to action at the end, in addition to a sentence or two to wrap everything up.

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +
This is a long post, from which I would remove nothing, so I suggest to include a TOC here, with links for the reader to jump straight to the section they are most interested in.

2022-01-28 10:34 UTC, tobyhodges commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +title: "First Draft of The Carpentries Workbench"
```suggestion
title: "Introducing The Carpentries Workbench"
```

You mention it's a first draft in the teaser, which will appear as a subtitle on the page.

2022-01-28 15:41 UTC, fmichonneau reviewed
Excellent work on this post Zhian! It does a good job of capturing the exciting new features of the infrastructure.

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +template from the ground up that clearly separates the tools from the content.
```suggestion
infrastructure from the ground up that clearly separates the tools from the content.
```

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +Pandoc in three custom packages called [{sandpaper}], [{varnish}], and
add link to pandoc for people not familiar with it?

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +more about the process we used for validating that the infrastructure, you can
```suggestion
more about the process we used for validating the infrastructure, you can
```

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +soft beta release April 2022** with interested maintainers, lesson authors, and
```suggestion
soft beta release in April 2022** with interested maintainers, lesson authors, and
```

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +instructor notes, but this page is often buried in the "extras" dropdown menu
```suggestion
instructor notes, but this page is often buried in the "extras" dropdown menu.
Because it is out of sight, it is not used often, and goes out of sync with the
content of the lesson.
```

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +and while it is useful to have the overview, the new infrastructure offers a way
```suggestion
And while it is useful to have an overview of all the tips to teach a lesson, the new infrastructure offers a way
```

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +note sprints for our instructors to share their knowledge and contribute to the
```suggestion
note sprints for our Instructors to share their knowledge and contribute to the
```

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +OMAR PLEASE HELP THING OF A GOOD ENDING
Also, we need a mention that this work is funded by CZI Science.

2022-01-28 15:41 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +up-to-date lessons in any lanuguge (both human and computer).
this paragraph about future plans might be a  good place to add a mention that the LIC will start their activities again as we get closer to release, and pointing to your blog post on the topic.

2022-01-28 17:13 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +principles][design-principles], The Carpentries Workbench is built with R and
add comment that people can use the template without knowing R (like they use the template now without knowing Ruby)

2022-01-28 18:28 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +specific commits).
I don't feel bad about this at all! Less inherent responsibility for me!

2022-01-28 18:30 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +developers towards the pit of success in terms of creating accessible and
That is a good point! I meant to link it. https://engineering.rice.edu/news/hadley-wickham-identifies-good-design-data-science

2022-01-28 18:30 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +developers towards the pit of success in terms of creating accessible and
```suggestion
developers towards the [pit of success](https://engineering.rice.edu/news/hadley-wickham-identifies-good-design-data-science) in terms of creating accessible and
```

2022-01-28 18:30 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +up-to-date lessons in any lanuguge (both human and computer).
sruly I maent lanuguge

2022-01-28 18:31 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +OMAR PLEASE HELP THING OF A GOOD ENDING
Hai @kmomar 👋🏼

2022-01-28 18:33 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +title: "First Draft of The Carpentries Workbench"
I thought I added this in the previous commit, but github was being wah

2022-01-28 18:39 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +template from the ground up that clearly separates the tools from the content.
Thought I included this in the earlier batch 🤦🏼

2022-01-28 18:57 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +
Done!

2022-01-28 19:17 UTC, kmomar commented
@zkamvar the links aren't rendering in the preview version. Will they show up correctly once the blog post is merged?

2022-01-28 19:18 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +</figure>
done

2022-01-28 19:20 UTC, zkamvar commented
> @zkamvar the links aren't rendering in the preview version. Will they show up correctly once the blog post is merged?

I have just pushed something that may fix it... honestly it's a mystery because Kramdown is really the Vince Vega of markdown interpreters.

2022-01-28 19:27 UTC, kmomar commented
> > @zkamvar the links aren't rendering in the preview version. Will they show up correctly once the blog post is merged?
> 
> I have just pushed something that may fix it... honestly it's a mystery because Kramdown is really the Vince Vega of markdown interpreters.

Hmm it seems they're rendering correctly now, but a lot of them lead to 404s.

2022-01-28 19:27 UTC, zkamvar commented
> > > @zkamvar the links aren't rendering in the preview version. Will they show up correctly once the blog post is merged?
> > 
> > 
> > I have just pushed something that may fix it... honestly it's a mystery because Kramdown is really the Vince Vega of markdown interpreters.
> 
> Hmm it seems they're rendering correctly now, but a lot of them lead to 404s.

Try it again! I just pushed a new update and It's working for me

2022-01-28 19:50 UTC, kmomar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +OMAR PLEASE HELP THING OF A GOOD ENDING
Add something like:

### How you can help 
- If you are interested in beta testing The Carpentries Workbench and providing valuable feedback as we iterate on the infrastructure, please contact zkamvar@carpentries.org
- If you find any errors in the infrastructure, please consider opening an issue on the repository (link) 
- Please continue providing feedback on the work outlined above 

Thank you to our community who has been instrumental in calling for these changes, and in advance for helping The Carpentries as we transition to a more equitable and accessible lesson infrastructure. Thank you also to [CZI Science](https://chanzuckerberg.com/science/) for their support and funding for this work.

2022-01-28 21:30 UTC, acrall approved these changes
Looks great, @zkamvar! Being new to GitHub, not sure how you add alt text to images, but  be sure those are included for screen readers if you have not already.

2022-01-28 21:30 UTC, acrall commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +instructors. **If you would like to begin exploring The Carpentries Workbench
Our style guide has us capitalise all volunteer roles so should check on that throughout

2022-01-28 21:30 UTC, acrall commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +OMAR PLEASE HELP THING OF A GOOD ENDING
Would you be interested in scheduling a Community Discussion for this? Seems it would be a good themed topic that we could get scheduled whenever is convenient for you. No worries if you prefer not to....just a thought.I can work with you to get it added to the Community Calendar and Etherpad and help pull something together so we get good feedback during the call

2022-01-28 23:06 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +instructors. **If you would like to begin exploring The Carpentries Workbench
Good catch! I'll fix that!

2022-01-28 23:15 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +OMAR PLEASE HELP THING OF A GOOD ENDING
Yes I would! We discussed these in the last Curriculum Team Meeting. I'm not sure when they should be, but we do know that they should be targetted to specific members of the community so that we can highlight and discuss aspects of the workbench that are relative for that community (e.g. while members of the Instructor community will be tangentially interested in the build process for the lessons, the main topics of focus will be the navigational features of the lessons, the instructor view, and future features such as handouts and/or slides).

2022-01-28 23:26 UTC, zkamvar commented
@kmomar, I leave this in your capable hands.

2022-01-29 02:53 UTC, zkamvar commented
It's in your capable hands, @kmomar as long as @tobyhodges approves of the changes he requested!

2022-01-29 05:44 UTC, tobyhodges approved these changes

2022-01-31 10:47 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +soft beta release in April 2022** with interested Maintainers, Lgsson Authors, and
```suggestion
soft beta release in April 2022** with interested Maintainers, Lesson Authors, and
```

2022-01-31 10:54 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +[new-episodes]: https://web.archive.org/web/20220127011238/https://carpentries.github.io/sandpaper-docs/episodes.html
this link does not work (it says "The Wayback Machine has not archived that URL.")

2022-01-31 10:55 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +With the new lesson infrastructure, changes, even major changes are applied
```suggestion
With the new lesson infrastructure, changes to the styling, even major changes are applied
```

2022-01-31 10:56 UTC, fmichonneau commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +Zhian is going to implement and fill this in on Friday :weary:
update or remove section?

2022-01-31 15:20 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +Zhian is going to implement and fill this in on Friday :weary:
let's remove it

2022-01-31 15:40 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +Zhian is going to implement and fill this in on Friday :weary:
There is still a weird bug with rendering in RStudio cloud, so I'm going to just delete this

```suggestion
```

2022-01-31 15:40 UTC, zkamvar commented on _posts/2022/01/2022-01-31-live-lesson-infrastructure.md
> +[new-episodes]: https://web.archive.org/web/20220127011238/https://carpentries.github.io/sandpaper-docs/episodes.html
```suggestion
[new-episodes]: https://carpentries.github.io/sandpaper-docs/episodes.html
```

2022-01-31 16:07 UTC, merged