Create 2022-03-02-incubator-lesson-spotlight-intermediate-research-so…
carpentries/carpentries.org-archive pull request #1341
Opened 2022-02-24 20:20 UTC by kmomar

2022-02-24 21:22 UTC, MCMaurer commented
Hi @anenadic and @steve-crouch, I've written up your submission to the Incubator Lesson Spotlight into a blog post. If you could take a quick look over it to verify that everything is correct or update anything you'd like, that would be fantastic. Let me know if you have any questions!

2022-02-28 08:33 UTC, anenadic commented
Hi @MCMaurer - thank you very much for this! There are a couple of updates to the text:
- sentence "All the lessons have been completely written and piloted in 3 workshops." - the course has now been piloted 5 times (including one time in an industrial setting for AstraZeneca)
- "We are doing final checks for language, diagram and snapshots and code output consistency, and finalising instructor notes. It is ready for reuse by the community and can be either delivered in code-along setting or as self-learning course." - code, snapshots and proofreading has been finalised, the only thing left is updating the instructor notes.

2022-02-28 22:41 UTC, MCMaurer requested changes
Just a few small changes per author request.

2022-02-28 22:41 UTC, MCMaurer commented on _posts/2022/03/2022-03-02-incubator-lesson-spotlight-intermediate-research-software-development-in-python.md
> +All the lessons have been completely written and piloted in 3 workshops. We are doing final checks for language, diagram and snapshots and code output consistency, and finalising instructor notes. It
Recommend changing to:

>All the lessons have been completely written and piloted in 5 workshops, including one time in an industrial setting. We are currently working on finalising instructor notes. It is ready for reuse by the community and can be delivered in code-along setting, but we have found it works best as a self-learning course for learners with previous programming experience, with helpers in attendence to aid learners where necessary.

2022-02-28 22:42 UTC, MCMaurer commented
Hi @anenadic, I've requested a few changes to the PR, if you want to review that language and let me know if it needs any further modification, please let me know!

2022-03-01 12:44 UTC, anenadic commented on _posts/2022/03/2022-03-02-incubator-lesson-spotlight-intermediate-research-software-development-in-python.md
> +All the lessons have been completely written and piloted in 3 workshops. We are doing final checks for language, diagram and snapshots and code output consistency, and finalising instructor notes. It
Sounds good @MCMaurer - here is a small tweak + a typo fix for your consideration:

All the lessons have been completely written and piloted in 5 workshops, including one time in an industrial setting. We are currently working on finalising instructor notes. It is ready for reuse by the community and, while the course  be delivered in a code-along setting, we have found it works best as a self-learning course for learners with previous programming experience, with helpers in attendance to aid learners where necessary.

2022-03-01 12:45 UTC, anenadic commented
> 

Small tweak suggested - otherwise good to go. Cheers @MCMaurer!

2022-03-02 16:38 UTC, merged