add workbench beta blog post
carpentries/carpentries.org-archive pull request #1375
Opened 2022-04-25 19:15 UTC by zkamvar

This is a draft of an announcement for the Beta Phase of the Workbench.

2022-04-26 20:11 UTC, fmichonneau requested changes
Thanks Zhian! This is an information-packed but clear post.

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +tags: ["Lesson Infrastructure", "Community", "Carpentries Workbench", "Beta", "Dovetail"]
I :heart: the come back of the dovetail!

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +We will be transitioning some of the lessons to The Carpentries Workbench in the
```suggestion
We will be transitioning some of the lessons to [The Carpentries Workbench](https://carpentries.org/blog/2022/01/live-lesson-infrastructure/) in the
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +We expect to transition all lessons (including incubator and lab) to use [The
```suggestion
We expect to transition all lessons (including lessons in The Carpentries Incubator and The Carpentries Lab) to use [The
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +maitnainers to volunteer for beta testing The Carpentries Workbench on their own
```suggestion
maintainers to volunteer for beta testing The Carpentries Workbench on their own
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +only be achieved if we use it on a variety of lessons and maintainers. **The
```suggestion
only be achieved if it is being used on a variety of lessons and tested by multiple maintainers. **The
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +purpose of the beta phase is to test out the workbench in conditions that I have
```suggestion
purpose of the beta phase is to test out the workbench in live conditions.**
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +no control over.** Thus, we would like to get a breadth of lessons using The
```suggestion
Thus, we would like to get a breadth of lessons using The
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +  lessons from 2015--Present: <https://carpentries.github.io/lesson-example/>.
```suggestion
  lessons since 2015: <https://carpentries.github.io/lesson-example/>. 
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +A lesson release is baked into a zenodo DOI (by François), [the lesson
```suggestion
A lesson release is minted into a zenodo DOI (by François), [the lesson
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +### Cognative Load
```suggestion
### Cognitive Load
```

2022-04-26 20:11 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +2. Maintainers can practice giving feedback via friction logs in paired
maybe add a little bit more information about when/how these sessions will take place?

2022-04-26 23:58 UTC, zkamvar commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +no control over.** Thus, we would like to get a breadth of lessons using The
You can make suggestions over multiple lines by clicking and dragging down.

2022-04-27 00:02 UTC, zkamvar commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +A lesson release is baked into a zenodo DOI (by François), [the lesson
https://twitter.com/Hao_and_Y/status/1496859917558317058

2022-04-27 00:03 UTC, zkamvar commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +2. Maintainers can practice giving feedback via friction logs in paired
I would if I had the information 😅

2022-04-27 14:24 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +  - New Instructors: encouraged to contribute to beta phase by adding/moving instructor notes
```suggestion
  - Checkout for new Instructors: encouraged to contribute to beta phase by adding/moving instructor notes
```

what would be the best way to communicate with Trainers to encourage this with new Instructors?

2022-04-27 14:27 UTC, fmichonneau commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +2. Maintainers can practice giving feedback via friction logs in paired
then maybe add that more information about this will be coming soon

2022-04-27 15:30 UTC, zkamvar commented on _posts/2022/05/2022-05-02-workbench-beta.md
> +  - New Instructors: encouraged to contribute to beta phase by adding/moving instructor notes
Probably directly communicating to the trainers channel on slack and topicbox

2022-05-02 19:19 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +In the end, we will transition all lessons by January 2022. The beta phase is
```suggestion
In the end, we will transition all lessons by January 2023. The beta phase is 
```

2022-05-02 19:19 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +workbench, understanding the advantages and limitations of the workbench can
```suggestion
workbench, understanding the advantages and limitations of the Workbench can
```

2022-05-02 19:21 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +During the workbench beta phase, the URLs for the styles and the workbench
```suggestion
During the Workbench beta phase, the URLs for the styles and the workbench
```

2022-05-02 19:24 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +preparing lessons. Feedbare invited give teaching-demo style feedback (**TBA**)
I think something is a little off with this sentence.

2022-05-02 19:27 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +branch will be copied to a static branch called “legacy”. The styles version of
```suggestion
using the [lesson transition tool][lesson-transition]. The branch holding the styles version
of the website will be copied to a static branch called “legacy”. The styles version of
```

2022-05-02 19:34 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +the website will have a banner that announces that an up-to-date version of the
not sure about this one.
```suggestion
the website will have a banner that announces that a newer version of the
```

2022-05-02 19:36 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +website can be found at the workbench URL with a link for feedback.
currently, there is no link for feedback in the banner. And if people navigate away from that page it is unlikely they go back to provide feedback on the Workbench version.

```suggestion
website can be found at the workbench URL. 
```

2022-05-02 19:37 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +submitting Instructor notes inside the lesson content.
```suggestion
**New Instructors** will be encouraged to contribute to the lessons by
submitting Instructor notes inside the lesson content for their checkout.
```

2022-05-02 19:38 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +the new version of the lesson and any future workshops will use this version.
```suggestion
the Workbench version of the lesson and any future workshops will use this version.
```

2022-05-02 19:39 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +translation process, but it will contain the correct content.
I would remove this sentence as it might make things more confusing to readers.

2022-05-02 19:39 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +only ONE lesson is different from the others. We mitigate this by having two
```suggestion
only one lesson is different from the others. We mitigate this by having two
```

2022-05-02 19:41 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +using it without worrying about doing any permanent damage.
```suggestion
using it without worrying about affecting the lessons taught in our workshops.
```

2022-05-02 19:44 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +workbench in live conditions and get feedback from early adopters.** Thus, we
```suggestion
Workbench in live conditions and get feedback from early adopters.** Thus, we
```

2022-05-02 19:44 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +: The beta phase of the workbench transition. This explicitly does NOT mean beta
```suggestion
: The beta phase of the Workbench transition. This explicitly does NOT mean beta
```

2022-05-02 19:45 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +intended to allow early adopters to play around with the workbench and help
```suggestion
intended to allow early adopters to play around with the Workbench and help
```

2022-05-02 19:50 UTC, zkamvar commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +preparing lessons. Feedbare invited give teaching-demo style feedback (**TBA**)
I think the primary thing that's off is the fact that "Feedbare" is not a word in any language. 

```suggestion
preparing lessons. Instructors interested in practising with the Workbench are invited give teaching-demo style feedback (**TBA**)
```

2022-05-02 19:53 UTC, fmichonneau reviewed
sorry for the mix of "single comments" and "review comments" but I left a few minor suggestions for edits (mostly for consistency). Feel free to approve them or leave them!

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +The workbench beta phase is **non-reversible**[^1], thus, the descision to begin
```suggestion
The Workbench beta phase is **non-reversible**[^1], thus, the decision to begin
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +  The styles and workbench versions of the websites will live in parallel at separate URLs during the first two stages of the workbench beta phase
```suggestion
  The styles and Workbench versions of the websites will live in parallel at separate URLs during the first two stages of the Workbench beta phase
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +- [Beta](#beta): lesson-release and archive of styles version; source conversion to workbench
```suggestion
- [Beta](#beta): lesson-release and archive of styles version; source conversion to Workbench
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +  - New Instructors: encouraged to contribute to workbench beta phase by adding/moving Instructor notes
```suggestion
  - New Instructors: encouraged to contribute to the Workbench beta phase by adding/moving Instructor notes
    as part of their checkout
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +- [Release Candidate](#release-candidate): fully transition to workbench and new URL; old URL will redirect to new.
```suggestion
- [Release Candidate](#release-candidate): fully transition to the Workbench and new URL; old URL will redirect to new.
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +An overview of the workbench beta phase for the Git repository and the website, separated
```suggestion
An overview of the Workbench beta phase for the Git repository and the website, separated
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +to the workbench beta phase. Importantly, they should **begin the process of
```suggestion
to the Workbench beta phase. Importantly, they should **begin the process of
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +**Instructors** can opt in to using the workbench version when teaching or
```suggestion
**Instructors** can opt in to using the Workbench version when teaching or 
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +**Maintainers** will work on the `main` branch of the lesson using the workbench
```suggestion
**Maintainers** will work on the `main` branch of the lesson using the Workbench
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +phase where the workbench exists as a sandbox so that Maintainers can practise
```suggestion
phase where the Workbench exists as a sandbox so that Maintainers can practise
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +The first few lessons in workbench beta will involve a lot of iteration and
```suggestion
The first few lessons in Workbench beta will involve a lot of iteration and
```

2022-05-02 19:53 UTC, fmichonneau commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +contributing to the workbench:
```suggestion
contributing to the Workbench:
```

2022-05-02 19:56 UTC, zkamvar reviewed
ugh, I accenentally clicked the "review" button instead of comment and now I'm stuck in review mode.

2022-05-02 19:56 UTC, zkamvar commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +website can be found at the workbench URL with a link for feedback.
Good point. Just to be safe, there should be a link to the Workbench discussion page on the banner. I will also put the link on all lessons in beta (and it's bringing up one of the things I really wish we asked for in the design phase: a mechanism for banners/alerts on the website)

2022-05-02 19:56 UTC, zkamvar commented on _posts/2022/05/2022-05-04-workbench-beta.md
> +translation process, but it will contain the correct content.
```suggestion
```

2022-05-05 16:45 UTC, merged