add dovetail blog post
carpentries/carpentries.org-archive pull request #1418
Opened 2022-06-07 01:05 UTC by zkamvar

This adds the next dovetail blog post. There were no updates from community members as I had not asked `-_-`.

@fmichonneau, @kmomar, and @tobyhodges, could you take a look and make sure this looks cromulent?

2022-06-07 09:28 UTC, fmichonneau approved these changes
This looks great to me!

2022-06-07 10:32 UTC, tobyhodges requested changes
I suggest a few minor changes, but otherwise this looks really good.

2022-06-07 10:32 UTC, tobyhodges commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +title: "The Dovetail: Updates from The Carpentries Workbench"
Is it a good idea to number these in the title, so that people get a quick impression of how many there are in the series?

2022-06-07 10:32 UTC, tobyhodges commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +This is the second post in a series of posts that we are calling "The Dovetail."
```suggestion
This is the second post in a series that we are calling "The Dovetail."
```

2022-06-07 10:32 UTC, tobyhodges commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +In this series, we aim to keep members of The Carpentries community abreast on
```suggestion
In this series, we aim to keep members of The Carpentries community abreast of
```

2022-06-07 10:32 UTC, tobyhodges commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +   destructive act, great care must be taken.
Can you link to somewhere community members can read more about the beta being "a destructive act"? I am not completely clear on what this means and the wording may be a little alarming for some readers!

2022-06-07 10:32 UTC, tobyhodges commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +```
❤️

2022-06-07 10:32 UTC, tobyhodges commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +rendered as markdown, so it makes more sense to use that as the figure caption.
Not sure what the correct wording should be, but "the markdown inside of `[]` can actually be rendered as markdown" is confusing to me.

2022-06-07 10:32 UTC, tobyhodges commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +The alt text first and formost is text that needs to be accessible, so
```suggestion
The alt text first and foremost is text that needs to be accessible, so
```

2022-06-07 16:14 UTC, zkamvar commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +   destructive act, great care must be taken.
```suggestion
   phase. It can enter lessons into pre-beta, but because [this transition is
   irreversible](https://github.com/data-lessons/lesson-transition#readme), great care must be taken.
```

2022-06-07 16:15 UTC, zkamvar commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +rendered as markdown, so it makes more sense to use that as the figure caption.
```suggestion
The reason for this is because the text inside of the square braces (`[]`) can actually be
rendered as markdown, so it makes more sense to use that as the figure caption, which can be formatted visually.
```

2022-06-07 16:25 UTC, zkamvar commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +title: "The Dovetail: Updates from The Carpentries Workbench"
```suggestion
title: "The Dovetail #2: Updates from The Carpentries Workbench"
```

2022-06-07 16:25 UTC, zkamvar commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +   destructive act, great care must be taken.
I've reworded it to say "irreversible" and link to the documentaiton

2022-06-07 16:26 UTC, zkamvar commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +rendered as markdown, so it makes more sense to use that as the figure caption.
I've updated the wording to use "text" and "square braces" so I don't repeat "markdown" twice

2022-06-08 07:46 UTC, tobyhodges approved these changes
Thanks @zkamvar 🙌

2022-06-08 15:10 UTC, zkamvar commented on _posts/2022/06/2022-06-08-dovtail-002.md
> +</figure>
```suggestion
![The author and his handsome son](fig/2022-06-08-author-cat.jpg){alt='A vertical
selfie photograph of Zhian (a Persian man) with thick-rimmed glasses and
short dark hair wearing headphones. His grey cat is sitting in his lap, looking
content as his head is being scratched.'}
```


<figure style="text-align: center">
  <img src="{{site.urlimg }}/blog/2022/06/2022-06-08-author-cat.jpg" 
   alt="A vertical selfie photograph of Zhian (a Persian man) with thick-rimmed glasses and short dark hair wearing headphones. His grey cat is sitting in his lap, looking content as his head is being scratched."/>
  <figcaption>
  The author and his handsome son
  </figcaption>
</figure>
```

2022-06-08 17:16 UTC, merged