dovetail number 006
carpentries/carpentries.org-archive pull request #1459
Opened 2022-08-16 01:00 UTC by zkamvar

2022-08-23 10:06 UTC, tobyhodges requested changes
Sets expectations and gives testers a bit more information about what they will be asked to do in the Beta 👍  I have made a few corrections and suggestions.

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +superficial aspects of the workbench itself.
```suggestion
superficial aspects of the Workbench itself. 
```

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +1. Creating awareness about The Workbench and [how workbench lessons differ from styles lessons](https://carpentries.github.io/workbench/transition-guide.html).
```suggestion
1. Creating awareness about The Workbench and [how Workbench lessons differ from _styles_ lessons](https://carpentries.github.io/workbench/transition-guide.html).
```

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +2. Providing a risk-free sandbox for maintainers to and instructors work with
```suggestion
2. Providing a risk-free sandbox for Maintainers and Instructors to work with
```

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +If we have the above two points, we know that we can proceed with the transition
```suggestion
If we have succeeded in the above two points, we know that we can proceed with the transition
```

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +more than simply making the community aware of the changes; we want to make
```suggestion
more than simply make the community aware of the changes; we want to make 
```

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +3. Make sure that the tool actually meets the needs and wants of the community.
```suggestion
3. Ensure that the tool actually meets the needs and wants of the community. 
```

Avoid repeating "make sure" in quick succession.

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +4. Create champions future contributors to The Workbench.
Not sure what you are trying to say here? Maybe "Inspire future contributors to The Workbench"?

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +4. Create champions future contributors to The Workbench.
How realistic is this as a goal for the Beta? I imagine future contributors would need to become familiar with the source code of the Workbench packages, and I don't think that is built into the current plan for the Beta?

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +}}/blog/2021/07/infrastructure-testing), my goal was to simply make sure that
```suggestion
}}/blog/2021/07/infrastructure-testing), my goal was to make sure that
```

Don't undersell yourself - it didn't look simple to me!

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +Workbench repository. For an extra level of detail, I am hoping that I can find
```suggestion
During each stage, I will be asking Maintainers and Instructors to
try out different, specific, tasks and give feedback in GitHub Issues on 
[The Workbench repository](https://github.com/carpentries/workbench).
For an extra level of detail, I am hoping that I can find
```

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +some maintainers or instructors to provide [Friction Logs](https://github.com/carpentries/workbench/discussions/2),
```suggestion
some Maintainers or Instructors to provide [Friction Logs](https://github.com/carpentries/workbench/discussions/2),
```

2022-08-23 10:06 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +exact cause of the friction can be identified and smoothed out.
```suggestion
exact causes of friction can be identified and smoothed out.
```

2022-08-23 13:49 UTC, zkamvar commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +4. Create champions future contributors to The Workbench.
This is a good point. Its less of a goal and more of a side-effect from transparently fixing issues and crediting community members in places where they were having trouble.  I've updated the wording to reflect this aspiration.

```suggestion
4. Create champions of, and inspire future contributors to The Workbench.
```

2022-08-23 14:32 UTC, tobyhodges approved these changes

2022-08-23 20:21 UTC, kmomar requested changes
Just some short copy edits! Great work @zkamvar

2022-08-23 20:21 UTC, kmomar commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +
We should add a sentence and link around this area to the rest of the posts if people are interested

2022-08-23 20:21 UTC, kmomar commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +not that much on The Workbench side of things. I atteneded and [presented at RStudio conference 2022](https://zkamvar.netlify.app/talk/carpentries-rstudio-2022/),
```suggestion
not that much on The Workbench side of things. I attended and [presented at the RStudio conference 2022](https://zkamvar.netlify.app/talk/carpentries-rstudio-2022/),
```

2022-08-23 20:21 UTC, kmomar commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +took a short staycation to decompress (with a broken aircon, no less!),
```suggestion
took a short "staycation" to decompress (with a broken aircon, no less!),
```

2022-08-24 02:54 UTC, zkamvar commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +
I agree. Do you want to add this before you merge?

2022-08-24 05:48 UTC, tobyhodges commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +the current news for [The Carpentries Workbench](https://carpentries.github.io/workbench).
```suggestion
This is the sixth post in [a series that we are calling "The Dovetail",
about the transition to The Carpentries Workbench](https://carpentries.org/posts-by-tags/#blog-tag-dovetail).
In this series, we aim to keep members of The Carpentries community abreast of
the current news about [the Workbench](https://carpentries.github.io/workbench). 
```

2022-08-24 14:16 UTC, zkamvar commented on _posts/2022/08/2022-08-24-dovetail-006.md
> +
It looks like toby made the changes. Feel free to merge

2022-08-24 16:55 UTC, kmomar approved these changes

2022-08-24 16:56 UTC, merged