add dovetail 9
carpentries/carpentries.org-archive pull request #1498
Opened 2022-10-17 23:29 UTC by zkamvar

This adds dovetail number 9, the first after the beta phase launch

2022-10-20 19:29 UTC, maneesha commented
@kmomar  should this have been merged yesterday?

2022-10-20 19:55 UTC, kmomar commented
@zkamvar Is this edition reviewed by Toby and ready to post?

CC: @maneesha

2022-10-20 22:17 UTC, zkamvar commented
It has not been reviewd by Toby because I failed to tag him 😞

2022-10-21 04:58 UTC, tobyhodges requested changes
Only a few minor fixes and one hanging sentence that needs finishing or removing. Otherwise, this is great and rather exciting!

2022-10-21 04:58 UTC, tobyhodges commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +maintainers of the lesson to practise working with the new infrastructure before
```suggestion
Maintainers of the lesson to practise working with the new infrastructure before
```

2022-10-21 04:58 UTC, tobyhodges commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +be converted to using The Workbech. During this time, the default URL will serve
```suggestion
be converted to using the Workbench. During this time, the default URL will serve
```

2022-10-21 04:58 UTC, tobyhodges commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +For instructors, here is a video showing what you can expect to see when you go
```suggestion
For Instructors, here is a video showing what you can expect to see when you go
```

2022-10-21 04:58 UTC, tobyhodges commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +   - Weekly updates to
Seems like a hanging sentence?

2022-10-21 04:58 UTC, tobyhodges commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +You would see a menu that prompts to to move the episode:
```suggestion
You would see a menu that prompts you to move the episode: 
```

2022-10-21 13:01 UTC, kmomar commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +You would see a menu that prompts to to move the episode:
Great@ @tobyhodges @zkamvar let's publish this next week rather than today.

2022-10-21 13:13 UTC, zkamvar commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +   - Weekly updates to
Monday was not a good day for me clearly

2022-10-21 20:59 UTC, zkamvar commented on _posts/2022/10/2022-10-19-dovetail-009.md
> +   - Weekly updates to
```suggestion
   - Weekly workflow file pull requests no longer result in pull requests with only sandpaper-version.txt changed.
```

2022-10-24 09:06 UTC, tobyhodges approved these changes

2022-10-24 14:06 UTC, merged