dovetail number 10
carpentries/carpentries.org-archive pull request #1506
Opened 2022-10-31 22:25 UTC by zkamvar

This adds dovetail number 10, which announces the release of R-socialsci and R-raster-vector-geospatial

2022-11-01 08:30 UTC, tobyhodges requested changes
Looks good. Mostly polishing changes to be made, but I think the alt-text on the alert box screenshot needs some more work, e.g. quotation marks replaced with `&quot`s.

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +<img alt='screencapture of pre-beta alert box on a Workbench site with a yellow caution icon followed by the text "Workbench Beta | Give Feedback | Learn More". The "give feedback" and "learn more' s
Seems like the alt-text cuts off abruptly? Also, watch out for which quote marks you are using to open/close the alt text string and to signify quotes within that string.

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +Alert banner displayed for lessons in workbench pre-beta stage
```suggestion
Alert banner displayed for lessons in Workbench pre-beta stage
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +In the next two weeks, we will see the following lessons enter the Beta Phase:
```suggestion
In the next two weeks, we will see the following lessons enter the beta phase:
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +During the Beta Phase, there will be two parallel sites available for 12 weeks,
```suggestion
During the beta phase, there will be two parallel sites available for 12 weeks,
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +Given that we value all contributions, this question is quite pertinant.
```suggestion
Given that we value all contributions, this question is quite pertinent. 
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +Given that we value all contributions, this question is quite pertinant.
This wording feels a little clunky to me. Suggest to change to something like "We value all contributions, and do not want the beta phase to introduce a barrier that could prevent a community member from improving a lesson.

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +suggestion to the lesson.
```suggestion
If someone clicks on a link, makes a suggested change, and opens a pull request,
it would be demotivating to find out that the contribution was made to a
temporary or frozen version of the lesson. Thus, the [answer to this question](https://github.com/carpentries/workbench/discussions/30#discussioncomment-3955501) 
is that clicking on the "improve this page" or "edit this page" buttons will
lead contributors to a landing page that briefly explains the purpose of the
phase they entered the lesson through and provides a link to follow to make their
suggestion to the lesson.
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +<a src="https://carpentries.github.io/workbench/contributor/beta.html?id=https://github.com/datacarpentry/r-socialsci/edit/main/_episodes_rmd/00-intro.Rmd">The beta snapshot page</a>
```suggestion
<a src="https://carpentries.github.io/workbench/contributor/beta.html?id=https://github.com/datacarpentry/r-socialsci/edit/main/_episodes_rmd/00-intro.Rmd">the beta snapshot page</a>
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +<a src="https://carpentries.github.io/workbench/contributor/pre-beta.html?id=https://github.com/fishtree-attempt/r-socialsci/edit/main/episodes/00-intro.Rmd">The pre-beta snapshot page</a>
```suggestion
<a src="https://carpentries.github.io/workbench/contributor/pre-beta.html?id=https://github.com/fishtree-attempt/r-socialsci/edit/main/episodes/00-intro.Rmd">the pre-beta snapshot page</a>
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +   - Bugs in the workbench beta phase links have been fixed
```suggestion
   - Bugs in the Workbench beta phase links have been fixed
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +   - Links to edit pages on GitHub are now directed to a page that first explains the purpose of the Beta Phase.
```suggestion
   - Links to edit pages on GitHub are now directed to a page that first explains the purpose of the beta phase.
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +Lessons that use the workbench automatically use [the {renv}
```suggestion
Lessons that use the Workbench automatically use [the {renv}
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +for one fo the lessons that was released into pre-beta today. This error
```suggestion
for one of the lessons that was released into pre-beta today. This error
```

2022-11-01 08:30 UTC, tobyhodges commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +working directory to `site/built` where all of the intermidate markdown output
```suggestion
working directory to `site/built` where all of the intermediate Markdown output
```

2022-11-01 13:19 UTC, zkamvar commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +<img alt='screencapture of pre-beta alert box on a Workbench site with a yellow caution icon followed by the text "Workbench Beta | Give Feedback | Learn More". The "give feedback" and "learn more' s
```suggestion
<img alt='screencapture of pre-beta alert box on a Workbench site with a yellow caution icon followed by the text &quot;Workbench Beta | Give Feedback | Learn More&quot;. The &quot;give feedback&quot; and &quot;learn more&quot; are links in bold.' src='{{ site.urlimg }}/blog/2022/11/dovetail-010-pre-beta-alert.png' style='border: solid 1px gray; padding: 10px;' />
```

2022-11-01 13:30 UTC, zkamvar commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +Given that we value all contributions, this question is quite pertinant.
```suggestion
We value all contributions and do not want the beta phase to introduce a barrier that could prevent a community member from improving a lesson.
```

2022-11-01 14:43 UTC, tobyhodges approved these changes

2022-11-01 15:32 UTC, kmomar commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +<span style='font-size: xx-large;'>If you have used the workbench and would like to provide feedback, please
Is there a way to make this *slightly* smaller - I find that it's rendering weirdly on the site

2022-11-01 15:49 UTC, zkamvar commented on _posts/2022/11/2022-11-02-dovetail-010.md
> +<span style='font-size: xx-large;'>If you have used the workbench and would like to provide feedback, please
This can be edited with the font-size parameter in the span element (https://developer.mozilla.org/en-US/docs/Web/CSS/font-size). Not sure what you mean by 'weirdly', but I'll change it to 'large'

```suggestion
<span style='font-size: large;'>If you have used the workbench and would like to provide feedback, please
```

2022-11-02 19:29 UTC, zkamvar commented
@kmomar can this be merged?

2022-11-02 19:49 UTC, merged