Update pricing tables and membership FAQ
carpentries/carpentries.org-archive pull request #1601
Opened 2023-03-17 23:11 UTC by Talishask

In response to questions about pricing, a-la-carte pricing and discounts I've made a few updates to our current website.

The membership page has been updated as follows:
- A-la-carte pricing has been changed to Membership Add-On pricing only. The purpose of this update is to simplify the pricing table by showing only the member discounted add-on rates and remove a la carte pricing from the membership page.
- include a section describing the trainer discount

The membership FAQ has been updated as follows:
- update trainer discount information

The workshops page (@carpentries/core-team-workshop-admin) was updated to:
-  include an administration fee table 
- remove information directing folks to the membership page for pricing

The instructor training page (@carpentries/core-team-instructor-training) was updated to add a la carte pricing.

2023-03-17 23:13 UTC, Talishask commented
I'm adding each team lead as a reviewer. Each team should review this and share their feedback.

@ErinBecker @elletjies also

2023-03-20 14:01 UTC, maneesha commented
I'm making this a draft until all reviews are complete.

2023-03-21 00:11 UTC, sheraaronhurt approved these changes
WAT information is good to go

2023-03-22 06:57 UTC, elletjies approved these changes

2023-03-22 16:49 UTC, karenword commented on pages/become-instructor.md
> +Organisations may pay a fee to gain priority access to Instructor Training events and train a group of individuals. Once invoiced, we will create a unique registration code for your trainees to acces
```suggestion
Individuals and organisations may pay a fee to gain access to Instructor Training. Once invoiced, we will create a unique registration code that trainees can use to access registration for any event on our quarterly [Instructor Training Calendar](https://carpentries.github.io/instructor-training/training_calendar/index.html). 
```

2023-03-22 16:53 UTC, karenword commented on pages/become-instructor.md
> +Organisations may pay a fee to gain priority access to Instructor Training events and train a group of individuals. Once invoiced, we will create a unique registration code for your trainees to acces
I'd like to discuss the use of the word "priority" in the title but I think it's fine for now - we can replace it later if we come up with a better description.

2023-03-22 17:00 UTC, karenword commented on pages/become-instructor.md
> +| Low Income          | $375                               |
I suggest adding the for-profit pricing to the table, as I have struggled to locate this buried in the text in the past. Example:
```suggestion
| Low Income          | $375   
| For-profit Institutions | 4x regional pricing                            |
```

2023-03-23 00:19 UTC, ErinBecker requested changes
Thank you SO much for putting together this PR @Talishask. I think I've made a mess of my suggestions, so I'll summarize here. 

- I really like the clarity of the language you added to the membership page about Trainer discounts, but I think we should only have that information listed in one place, so I'd like to see your language moved to the FAQ and then link to that section of the FAQ directly from the Trainer Discount section of the Membership page. 
- We need to be careful not to list the Trainer discount as a set monetary value because it will be a different value for members in different countries. Please list as "the value of six (6) seats in Instructor Training"
- I really like the separation of the costs for Membership add on fees and workshops.

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<p>All membership levels are customizable. Members have access to discounted rates and may add Centrally-Orgnised Workshops or Instructor Training seats to their membership at time.</p>
```suggestion
<p>All membership levels are customizable. Members have access to discounted rates and may add Centrally-Orgnised Workshops or Instructor Training seats to their membership at any time.</p>
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<p>Member organisations with active Instructor Trainers (also referred to as Trainers) may be eligible for a discount on their membership.</p>
```suggestion
<p>Member organisations with active Instructor Trainers (also referred to as Trainers) may be eligible for a discount on their membership. For more details see [our FAQ](/member_faq/#are-any-other-discounts-available).</p>
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<p>For each Trainer who meets the eligibility requirements above, you choose one of the following:</p>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +  <ul>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +    <li>Add six (6) instructor training seats to the membership or</li>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +    <li>Reduce the membership fee by $5,400 <i>(only if the total membership fee remains greater than or equal to $0)</i></li>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +  </ul>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<p><strong>Trainer Eligibility Requirements</strong></p>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<p>In the 1 year prior to renewal, Trainers who have completed the following are eligible for an organisational discount:</p>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<ul>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +  <li>teach at least 2 Instructor Training events for the global Carpentries community,</li>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +  <li>host at least 2 teaching demonstrations for the global Carpentries community, and</li>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +  <li>attend virtual Trainer community meetings</li>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +</ul>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<p>If the Trainer received their certification less than 1 year before renewal, the above acitivies will be prorated.</p>
```suggestion
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/membership.html
> +<p>Member organisations with active Instructor Trainers (also referred to as Trainers) may be eligible for a discount on their membership.</p>
I recommend that we remove the details on Trainer discount from the Membership page and link directly to the relevant answer in the FAQ.

2023-03-23 00:19 UTC, ErinBecker commented on pages/member_faq.md
> +* teach at least 2 Instructor Training events for the global Carpentries community,
```suggestion
* teach at least two (2) Instructor Training events for the global Carpentries community,
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/member_faq.md
> +* host at least 2 teaching demonstrations for the global Carpentries community, and
```suggestion
* host at least two (2) teaching demonstrations for the global Carpentries community, and
```

2023-03-23 00:19 UTC, ErinBecker commented on pages/member_faq.md
> +* host at least 2 teaching demonstrations for the global Carpentries community, and
I really liked the clarity with which this discount was described in the draft of the membership page, but want to have them only listed in one place. I've (tried to) moved the language that was proposed to the membership page to the FAQ and to link from the trainer discount section of the membership page directly to this part of the FAQ. I'm not sure if I was successful.

2023-03-24 23:08 UTC, Talishask commented on pages/become-instructor.md
> +| Low Income          | $375                               |
We are following common practice on this and the majority of our community organisations (all but 1-2) are non-profit institutions so my recommendation is to keep this only in the sentences around the table for now.

2023-03-24 23:11 UTC, Talishask commented on pages/membership.html
> +<p>All membership levels are customizable. Members have access to discounted rates and may add Centrally-Orgnised Workshops or Instructor Training seats to their membership at time.</p>
Great Catch on the missing word!

2023-03-24 23:26 UTC, Talishask commented
Thanks @ErinBecker and @karenword for the recommendations and updates. Are you both okay with this PR now?

One more question for @karenword: I would like to put the word "priority" back into the paragraph where we say what the organisation is paying for. We are an organisation that promotes open access and in reality our instructor training program is not closed. No one needs to pay for access. When members and organisations purchase training seats they are paying to speed up their access to the training - and that is being communicated in all other spaces as priority access. Thoughts on this?

2023-03-27 13:47 UTC, ErinBecker commented
Thank you for resolving my suggestions @Talishask. I took a look at the preview and saw that the Trainer Discount section of the Membership page isn't resolving correctly (screenshot below). Once this is fixed I'm happy with the changes!

<img width="1031" alt="Screen Shot 2023-03-27 at 6 46 14 AM" src="https://user-images.githubusercontent.com/19176319/227957414-4a0ea191-72b8-438d-8628-20194a7ccba1.png">

2023-04-14 01:35 UTC, ErinBecker commented
Thanks for that fix @Talishask. This addresses all of my comments and I'm happy to have this merged.

2023-04-17 21:52 UTC, karenword requested changes
I submitted a [PR to this branch](https://github.com/carpentries/carpentries.org/pull/1617) because I found a spot elsewhere on the become-instructor.md page that sent people to the membership page for group pricing. 

In addition, I'd like to have some kind of instruction on our page about who to contact for what, and I'm conflicted about where to put that. Options I considered:
- Under "Get an access code..." include a sentence like "Contact the Instructor Training team with requests for group training outside of membership."  OR
- Under "If you are seeking to train six..." add a sentence there, since that's really the point at which they have the information to decide which team to contact.

Finally, I wonder whether that ## Group Training... header should actually entirely go under the first numbered item, with Open Instructor Training below? But I don't have a strong opinion about this (especially with the coming redesign.)

2023-05-24 02:32 UTC, Talishask commented
@karenword - looks like we already included a note about "If you are seeking to train six or more...." so I think we are all set.
@ErinBecker  has communicated that she is okay with this update.

Can someone merge both pull requests? This one and https://github.com/carpentries/carpentries.org/pull/1617

2023-05-24 20:11 UTC, maneesha commented
I've merged #1617 in to this one, so I'm merging this now.

2023-05-24 20:11 UTC, merged