Create 2023-04-24-community-recognition.md
carpentries/carpentries.org-archive pull request #1618
Opened 2023-04-19 06:47 UTC by elletjies

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

2023-04-19 20:57 UTC, ErinBecker requested changes
Thanks @elletjies - this is looking great! I've made some suggested changes.

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +3, Provide opportunities for our volunteers and Core Team's growth and professional development.
```suggestion
3, Provide opportunities for our volunteers' and Core Team's growth and professional development.
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +to advance our mission. Are you following the Carpentries activities across Africa? Check out this
```suggestion
in advancing our mission. Are you following the Carpentries activities across Africa? Check out this 
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +across our global community (see [recommended changes](https://github.com/carpentries/trainers/issues/226)). We have also designated funds in our fiscal
```suggestion
across our global community (see [changes we are working to implement](https://github.com/carpentries/trainers/issues/226)). We have also designated funds in our fiscal 
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +year budget to translate key resources like the Code of Conduct. We are in our final round of functionality updates for our website (www.carpentries.org) and will soon move into community review and
```suggestion
year budget to translate key resources like the Code of Conduct. We are in our final round of functionality updates for our website and will soon move into community review and launch. And finally, in an effort to improve the accessibility of our workshops and community spaces, we developed an [Accessibility Accommodation Form](https://carpentries.typeform.com/to/B2OSYaD0) and released an [Accessibility Statement](https://carpentries.org/blog/2023/03/accessibility-statement-and-accommodation-form/). 
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +year budget to translate key resources like the Code of Conduct. We are in our final round of functionality updates for our website (www.carpentries.org) and will soon move into community review and
```suggestion
year budget to translate key resources like the Code of Conduct. We are in our final round of functionality updates for our website (www.carpentries.org) and will soon move into community review and launch. In May, we will launch our new lesson infrastructure, [The Carpentries Workbench](https://carpentries.github.io/workbench/), which prioritises accessibility. And finally, in an effort to improve the accessibility of our workshops and community spaces, we developed an [Accessibility Accommodation Form](https://carpentries.typeform.com/to/B2OSYaD0) and released an [Accessibility Statement](https://carpentries.org/blog/2023/03/accessibility-statement-and-accommodation-form/). 
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +We learned so much implementing CarpentryCon, including how beneficial skill-up sessions are for our community. We are excited to share that we’ll
```suggestion
We learned so much implementing CarpentryCon 2022, including how beneficial skill-up sessions are for our community. We are excited to share that we’ll 
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +development, and community building. We also launched a Supervisor Pilot Program for Core Team members interested in growing their supervisory skills.
```suggestion
development, and community building. Within the Core Team, we also launched a Supervisor Pilot Program for Core Team members interested in growing their supervisory skills.
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +Our new lesson infrastructure is to be rolled out on 1 May 2023, redesigned with a focus on accessibility and ease of maintenance. Additionally, we are
```suggestion
[The Carpentries Workbench](https://carpentries.github.io/workbench/), to be rolled out in May, greatly simplifies the process of contributing to lessons. Additionally, we are 
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +Maintainer onboarding program to support this essential role in the community better and established Curriculum Advisory Committees to guide the development of all official curricula.
```suggestion
Maintainer onboarding program to support this essential role in the community better, and established Curriculum Advisory Committees to guide the development of all official curricula.
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +We are proud to announce we are coordinating with the HPC Carpentry community on their application for lesson program incubation. Additionally, we have
```suggestion
We are proud to announce we are coordinating with the [HPC Carpentry](https://www.hpc-carpentry.org/) community on their application to become an official lesson program within The Carpentries. Additionally, we have 
```

2023-04-19 20:57 UTC, ErinBecker commented on _posts/2023/04/2023-04-24-community-recognition.md
> +We will continue to monitor and improve services, tools and virtual infrastructure to achieve reliability, efficiency and safety and security for our
```suggestion
We will continue to monitor and improve services, tools and virtual infrastructure to enhance reliability, efficiency and safety and security for our 
```

2023-04-20 06:22 UTC, elletjies commented
Thank you @ErinBecker!

2023-04-20 06:27 UTC, merged