report from EC f2f
carpentries/carpentries.org-archive pull request #176
Opened 2018-06-27 01:36 UTC by kcranston

Needs review from at least one other EC member @rgaiacs @ethanwhite @elliewix @k8hertweck @lexnederbragt @amyehodge @smcclatchy @mkuzak

2018-06-27 06:44 UTC, lexnederbragt reviewed
Great post capturing what we discussed. I've added a bunch of textual suggestions, mostly clarifications for newer members of the community.

2018-06-27 06:44 UTC, lexnederbragt commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +The Executive Council met face-to-face for the first time last week (June 18-19) in Gainesville. So, this seems like a good time to give everyone a sense of what we discussed at the in-person meeting
Gainesville, Florida in the US.

2018-06-27 06:44 UTC, lexnederbragt commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +First, I want to talk about the name 'Executive Council'. Why are we an EC, and not a 'Board of Directors'? In the US, that title has a specific meaning, and suggests financial and legal responsibili
In the US, a 'Board' has a specific meaning.

2018-06-27 06:44 UTC, lexnederbragt commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +Now that we're past the name, let's talk about the recent EC meeting in Florida. While we have been meeting online for the past few months, many members of the EC had not met face to face. An importa
While we have been meeting online for the past few months, and some of us met at CarpentryCon, many

build trust --> it sounds a bit like we didn't have any beforehand.

2018-06-27 06:44 UTC, lexnederbragt commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +We spent good chunk of the first day talking about Mission and Vision. We did a brainstorming session about what sort of world the Carpentries was trying to create, which produced many lists of goals
talking about Mission and Vision. We feel we need a Vision statement that expresses what is the future we are trying to achieve, and a set of Mission statements describing how we intend to get there.

Among the EC, most notable (, not .)

the next phase of that process --> please add that we are going to involve the community in this process as soon as possible!

2018-06-27 06:44 UTC, lexnederbragt commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +With a general consensus on vision and mission, we turned to strategic planning. Tracy, the Carpentries staff, and the many community leaders have been doing a heroic job running the new organization
Tracy Teal, the Executive Director of the Carpentries, together with the rest of the Carpentries staff,

the many community leaders -> maybe 'and the many folks from the community contributing their time to the organisation'?

1) arriving at the final mission & vision statement; 2) finalising the Carpentries bylaws (our set of rules by which we operate, more on that in another post); 3) elections for the next Executive Council; and 4) information gathering in preparation for long-term strategic planning.

2018-06-27 06:44 UTC, lexnederbragt commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +Just want to wrap up by saying that I am very excited about working with everyone on the EC. Over the two days in Gainesville, we navigated challenging conversations, heard a diversity of opinions, h
Would you be comfortable to add we did Irish dancing together?

2018-06-27 08:53 UTC, rgaiacs requested changes
Some minor changes.

2018-06-27 08:53 UTC, rgaiacs commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +title: "Report from First In-person Executive Council Meeting"
Change to

```
title: "Report from 2018 In-person Executive Council Meeting"
```

2018-06-27 08:53 UTC, rgaiacs commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +teaser: "Executive Council"
Change to

```
teaser: "Executive Council met in Gainesville to discuss mission and vision of The Carpentries."
```

2018-06-27 08:53 UTC, rgaiacs commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +tags: ["Mission", "Vision","Executive-council"]
Tags can have space, so we can use "Executive Council".

2018-06-27 08:53 UTC, rgaiacs commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +The Executive Council met face-to-face for the first time last week (June 18-19) in Gainesville. So, this seems like a good time to give everyone a sense of what we discussed at the in-person meeting
Replace

> The Executive Council

with

> The 2018 Executive Council

2018-06-27 08:53 UTC, rgaiacs commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +First, I want to talk about the name 'Executive Council'. Why are we an EC, and not a 'Board of Directors'? In the US, that title has a specific meaning, and suggests financial and legal responsibili
Change

> First, I want to talk about the name 'Executive Council'.

to

> First, I want to talk about the name 'Executive Council' (EC).

2018-06-27 08:53 UTC, rgaiacs commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +Now that we're past the name, let's talk about the recent EC meeting in Florida. While we have been meeting online for the past few months, many members of the EC had not met face to face. An importa
Change

> While we have been meeting online for the past few months, many members of the EC had not met face to face

to

> While we have been meeting online monthly since January, some members of the EC had not met others face to face.

2018-06-27 08:53 UTC, rgaiacs commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +With a general consensus on vision and mission, we turned to strategic planning. Tracy, the Carpentries staff, and the many community leaders have been doing a heroic job running the new organization
Replace

> now through next elections in winter 2018

with

> now through next elections in November, 2018

I think that we agreed to **not** use Summer, Fall, Winter or Spring as time reference because they aren't inclusive to our global community.

2018-06-27 12:04 UTC, kcranston commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +Now that we're past the name, let's talk about the recent EC meeting in Florida. While we have been meeting online for the past few months, many members of the EC had not met face to face. An importa
Yeah, I struggled a bit with this. Will re-word in the revision.

2018-06-27 12:10 UTC, kcranston commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +Just want to wrap up by saying that I am very excited about working with everyone on the EC. Over the two days in Gainesville, we navigated challenging conversations, heard a diversity of opinions, h
YES!

2018-06-27 12:13 UTC, kcranston commented on _posts/2018/06/2018-06-26-executive-council-meeting-report.md
> +With a general consensus on vision and mission, we turned to strategic planning. Tracy, the Carpentries staff, and the many community leaders have been doing a heroic job running the new organization
thanks so much for catching that!

2018-06-28 01:10 UTC, weaverbel commented
Is this now ready to merge @kcranston?

2018-06-28 01:11 UTC, kcranston commented
Yes, I believe so. Thanks!


On Wed, Jun 27, 2018, 21:10 Belinda Weaver <notifications@github.com> wrote:

> Is this now ready to merge @kcranston <https://github.com/kcranston>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/carpentries/carpentries.org/pull/176#issuecomment-400878796>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AATC4jz6QDMXAW1z1nZ2wsZ5Fda-yChMks5uBC0EgaJpZM4U47D2>
> .
>

2018-06-28 01:21 UTC, merged