added July dir and fee blog post
carpentries/carpentries.org-archive pull request #177
Opened 2018-06-29 14:53 UTC by smcclatchy

Hi,

I've added a blog post for self-organized fee removal, and would like @amyehodge and @maneesha to review, add to it, or contribute to its completion.

Sue

2018-06-29 15:29 UTC, amyehodge requested changes
A few comments and suggestions. The review workflow, which I've never used before, was the best way I found to do this. Hopefully, this works okay for you. I do not have permission to actually make changes.

2018-06-29 15:29 UTC, amyehodge commented on _posts/2018/07/2018-07-01-executive-council-drop-fee-motion.md
> +To bring Software and Data Carpentry self-organized workshop fees into agreement with one another, the 2018 Executive Council passed a motion to eliminate the $500 fee for self-organized Data Carpent
"To bring Software and Data Carpentry self-organized workshop fees into agreement with one another, the 2018 Executive Council passed a motion to eliminate the $500 fee charged **to host organizations** for self-organized Data Carpentry workshops."

2018-06-29 15:29 UTC, amyehodge commented on _posts/2018/07/2018-07-01-executive-council-drop-fee-motion.md
> +The fee for workshops centrally organized by Carpentries staff remains the same at $2500 USD. Carpentries staff take care of finding instructors to teach the workshop, help to finalize dates and curr
I think the lead instructor sets up the workshop website, so that's not a task of Carpentries staff and is the same whether centrally or self organized.

2018-06-29 15:29 UTC, amyehodge commented on _posts/2018/07/2018-07-01-executive-council-drop-fee-motion.md
> +To bring Software and Data Carpentry self-organized workshop fees into agreement with one another, the 2018 Executive Council passed a motion to eliminate the $500 fee for self-organized Data Carpent
I've bolded the text I am suggesting adding above. I don't intend it to be bolded in the post.

2018-06-29 15:29 UTC, amyehodge commented on _posts/2018/07/2018-07-01-executive-council-drop-fee-motion.md
> +Until 2018, Data Carpentry and Software Carpentry operated side-by-side but independently, each with their own governing bodies and executive directors. While the two organizations shared some proces
I would suggest replacing the last sentence here with this, leaving discussion of the finances for the last paragraph:

"To eliminate the confusion this has created within our community and to encourage self-organized workshops, we have brought these two policies into alignment by eliminating the $500 host organization fee from self-organized Data Carpentry workshops."

2018-06-29 15:29 UTC, amyehodge commented on _posts/2018/07/2018-07-01-executive-council-drop-fee-motion.md
> +# How is a self-organized workshop different from a centrally-organized one?
We had discussed getting some information from Maneesha about the requirements for branded workshops of any type. I think you've covered the difference between self-organized and centrally-organized succinctly.

2018-07-01 23:07 UTC, weaverbel commented
Can whoever finally reviews this please add the `Ready to merge` label when it is ready to go?

2018-07-02 15:15 UTC, maneesha commented on _posts/2018/07/2018-07-01-executive-council-drop-fee-motion.md
> +The fee for workshops centrally organized by Carpentries staff remains the same at $2500 USD. Carpentries staff take care of finding instructors to teach the workshop, help to finalize dates and curr
Correct.  The instructor sets up the website regardless of how the workshop is organized.

2018-07-02 15:17 UTC, maneesha commented
Can we not merge this until the corresponding workshop pages on the SWC and DC websites have been updated? Then we can merge everything at the same time so we don't have conflicting info anywhere.  I can fix those other pages by tomorrow.  Will update here when that's done.

2018-07-02 15:18 UTC, maneesha commented
When I talked with @tracykteal  about this at the last Carpentries staff meeting she said the resolution also did away with the Software Carpentry's suggested contribution of $500.  Is this correct?

2018-07-02 15:41 UTC, amyehodge commented
@maneesha yes, that is correct. Here is the exact wording of the motion for you: "The Carpentries Executive Council moves that The Carpentries are not charging or suggesting a fee to host organizations for self-organized Carpentries workshops."

2018-07-02 16:56 UTC, maneesha commented
Thanks @amyehodge 
Also, @tracykteal  said that we are also changing how we communicate about our corporate rates.  The SWC website has an explicity $10K fee; the DC website says to contact us.  We are changing both to say contact us, correct?

2018-07-02 17:10 UTC, amyehodge commented
@maneesha We did not discuss this, to my recollection, and I don't see any comments about it in the notes. This sounds to me like something that does not requires Exec Council input (others chime in if you disagree) and can be decided by staff.

2018-07-03 18:09 UTC, maneesha commented
I'd like to see the blog post updated to include that SWC fee structure (the suggested donation) is changing as well before this post goes live.  I have PRs in to both websites updating the website language:

https://github.com/datacarpentry/datacarpentry.github.io/pull/452
https://github.com/swcarpentry/website/pull/1058

2018-07-03 22:29 UTC, weaverbel commented
Those PRs now merged @maneesha

2018-07-04 09:29 UTC, rgaiacs commented on _posts/2018/07/2018-07-01-executive-council-drop-fee-motion.md
> +To bring Software and Data Carpentry self-organized workshop fees into agreement with one another, the 2018 Executive Council passed a motion to eliminate the $500 fee for self-organized Data Carpent
Replace

> To bring Software and Data Carpentry self-organized workshop fees into agreement with one another, ...

with

> To bring The Carpentries member lesson organisations self-organized workshop fees into agreement with one another, the Executive Council passed a motion to eliminate the $500 fee for self-organized workshops.

This language is more close to the motion that was approved and make clear that future member lesson organisations will also no charge a fee for self-organized workshops.

2018-07-09 21:07 UTC, weaverbel commented
Is this post ready to merge now @smcclatchy ?

2018-07-09 21:18 UTC, smcclatchy commented
@k8hertweck @kcranston @mkuzak @lexnederbragt @elliewix @ethanwhite please do final review for this blog post.

2018-07-09 21:23 UTC, k8hertweck commented
I'm happy with this! Thanks, folks.

2018-07-10 12:29 UTC, ethanwhite commented
Looks great! Nice work everyone!

2018-07-10 12:31 UTC, mkuzak commented
+1

2018-07-11 13:46 UTC, smcclatchy commented
We have approval from 4 of the EC members, so I'd say this is ready to merge @weaverbel. Thank you.

2018-07-11 21:45 UTC, merged