Re-publication of an external community member blog post on SwC localisation efforts in Ukrainian language.
carpentries/carpentries.org-archive pull request #1820
Opened 2024-05-17 20:08 UTC by OscarSiba

2024-05-17 21:10 UTC, kariljordan approved these changes
@OscarSiba this post looks great! So glad we were able to cross-post it.

2024-05-18 09:09 UTC, olexandr-konovalov approved these changes
@OscarSiba - just one typo to fix, everything else looks fine. Thank you!

2024-05-18 09:09 UTC, olexandr-konovalov commented on _posts/2024/05/2024-05-17-software-carpentries-translation-efforts-in-ukrain.md
> +_This blog post was orginally published on Dr. Olexandr Konovalov's website as ["Software Carpentry for Ukraine: status update"](https://olexandr-konovalov.github.io/posts/2024/04/18/ukrainian-carpen
typo: "modifciations"

2024-05-18 09:13 UTC, olexandr-konovalov requested changes
@OscarSiba can we also rename the file not to truncating "ukrain", please? Could end with "ukrainian" for more readable URL? If you want to shorten the URL to keep it within some length limit, maybe remove "efforts"?

2024-05-20 11:28 UTC, OscarSiba commented on _posts/2024/05/2024-05-17-software-carpentries-translation-efforts-in-ukrain.md
> +_This blog post was orginally published on Dr. Olexandr Konovalov's website as ["Software Carpentry for Ukraine: status update"](https://olexandr-konovalov.github.io/posts/2024/04/18/ukrainian-carpen
Thank you @olexandr-konovalov, will update.

2024-05-20 11:45 UTC, merged

2024-05-20 11:50 UTC, olexandr-konovalov commented
@OscarSiba perfect, thanks!