Announcing rewrite of the Library Carpentry Intro to Python lesson
carpentries/carpentries.org-archive pull request #1830
Opened 2024-06-07 15:11 UTC by jt14den

Blog on updated lc python lesson.

2024-06-18 15:30 UTC, OscarSiba commented
> Blog on updated lc python lesson.

Hi @jt14den, please hit ‘accept suggestion’ (and not ‘resolve’) for all suggestions you are happy to be incorporated into the final blog post. Most suggestions are changes from American to UK English spelling as per Carpentries style guide.

2024-06-25 07:42 UTC, OscarSiba commented
> > Blog on updated lc python lesson.
> 
> Hi @jt14den, please hit ‘accept suggestion’ (and not ‘resolve’) for all suggestions you are happy to be incorporated into the final blog post. Most suggestions are changes from American to UK English spelling as per Carpentries style guide.

Pinging you again @jt14den to check if you would be able to update this this week so we can publish it sometime during the week? Please update publication date to also reflect when it would be ready to go out.

2024-06-25 16:51 UTC, jt14den commented
@OscarSiba i'm not seeing anything to update on my end. Can you lmk what I need to do to move this forward? Thanks

2024-06-26 10:31 UTC, OscarSiba requested changes
Apologies @jt14den, @tobyhodges just made me realise I didn't actually submit my review, and it's been pending on my side all this time! Hope you see the suggested changes now!

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +date: 2024-06-15
```suggestion
date: 2024-06-26
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +The lesson demonstrates how to use Python to clean, analyze, and visualise library usage data, providing an introduction to reproducible workflows in Python for library and information workers. While
```suggestion
The lesson demonstrates how to use Python to clean, analyse, and visualise library usage data, providing an introduction to reproducible workflows in Python for library and information workers. While the lesson repurposes some elements from the previous Library Carpentry Introduction to Python, it is a major overhaul that includes a new library-specific dataset, the use of JupyterLab instead of Spyder, and new episodes that use Pandas to tidy a dataset and Plotly to visualise data. 
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +The updated lesson includes twelve substantive episodes that cover Python fundamentals such as variables, types, lists, functions, for loops, and conditionals. The lesson demonstrates how to import C
```suggestion
The updated lesson includes twelve substantive episodes that cover Python fundamentals such as variables, types, lists, functions, for loops, and conditionals. The lesson demonstrates how to import CSV files representing annual usage data from the Chicago Public Library system into Pandas, and focuses on wrangling, analysing, and visualising this quantitative dataset. Packages that are introduced include glob, Pandas, and Plotly. Along with Python fundamentals, learners will use Pandas to:
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +- Manipulate, clean, and analyze data
```suggestion
- Manipulate, clean, and analyse data
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +Python is a widely used language for data science tasks and is commonly leveraged for metadata and cataloging, collection analysis, assessment, and other related tasks in libraries. Python can be use
```suggestion
Python is a widely used language for data science tasks and is commonly leveraged for metadata and cataloguing, collection analysis, assessment, and other related tasks in libraries. Python can be used for web scraping, collecting data via Application Programming Interfaces (APIs), and to clean and organise data and metadata. As a popular tool in data science, computational social sciences, and digital humanities, Python is also a great toolkit for working with researchers across multiple disciplines.
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +The current Library Carpentry Python course has been developed, taught, and adapted by many past and present members of the Carpentries communities. The previous iteration of the lesson was adapted f
```suggestion
The current Library Carpentry Python course has been developed, taught, and adapted by many past and present members of The Carpentries communities. The previous iteration of the lesson was adapted from the Software Carpentry [Plotting & Programming in Python lesson](https://swcarpentry.github.io/python-novice-gapminder/), and was developed and maintained by Konrad Förstner, Drew Heles, Elizabeth Wickes, Laura Wrubel, Carlos Martinez and Richard Vankoningsveld. The current iteration was created by Cody Hennesy, Tim Dennis, Scott Peterson, and David Palmquist.
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +The LC-CAC approved the updated lesson based on its improved relevance to library and information workers, and the integration of more contemporary development practices and platforms. The maintainer
```suggestion
The LC-CAC approved the updated lesson based on its improved relevance to library and information workers, and the integration of more contemporary development practices and platforms. The Maintainers have collected and integrated learner and Instructor feedback from several pilot lessons, with plans to continue teaching the lesson in a number of in-person and online contexts.
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +We invite Carpentries instructors to teach the new lesson and provide feedback via the [repository Issues page](https://github.com/LibraryCarpentry/lc-python-intro/issues) or [by reaching out to the
```suggestion
We invite Carpentries Instructors to teach the new lesson and provide feedback via the [repository Issues page](https://github.com/LibraryCarpentry/lc-python-intro/issues) or [by reaching out to the Maintainers](https://github.com/LibraryCarpentry/lc-python-intro/blob/main/CONTRIBUTING.md). Our goal is to move the lesson from [beta to stable](https://carpentries.github.io/lesson-development-training/19-operations.html#the-lesson-life-cycle) over the next year. If you are interested in contributing to the lesson in an ongoing way, we welcome new Maintainers: reach out to the current Maintainers via the links above to discuss possibilities. If you have other ideas about building future Python lessons for Library Carpentry, and what modules should be included, please [contact the LC-CAC](https://github.com/LibraryCarpentry/curriculum-advisors?tab=readme-ov-file#how-to-contact-the-curriculum-advisory-committee). 
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +- Cody Hennesy is the Computational Research Librarian at the University of Minnesota, Twin Cities, where he supports researchers with reproducible and methodologically sound practices to collect and
```suggestion
- Cody Hennesy is the Computational Research Librarian at the University of Minnesota, Twin Cities, where he supports researchers with reproducible and methodologically sound practices to collect and analyse library and open digital collections. He is a member of the LC-CAC.
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +- Tim Dennis, the Director of the Data Science Center at UCLA Library, specializes in helping researchers and students apply computational and data methods. His work focuses on increasing access, sup
```suggestion
- Tim Dennis, the Director of the Data Science Center at UCLA Library, specialises in helping researchers and students apply computational and data methods. His work focuses on increasing access, supporting activism-minded research, and transforming data services through inclusive pedagogy and expanded familiarity with open source software.
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +- David Palmquist is Systems Analyst with the Pollak Library at Cal State University, Fullerton. Carpentries instructor, maintainer, and member of the CSU Carpentries Collective which strives to expa
```suggestion
- David Palmquist is Systems Analyst with the Pollak Library at Cal State University, Fullerton. He is a Carpentries Instructor, Maintainer, and member of the CSU Carpentries Collective which strives to expand Carpentries workshop opportunities delivered by CSU faculty and staff.
```

2024-06-26 10:31 UTC, OscarSiba commented on _posts/2024/06/2024-06-15-lc-python-update.md
> +date: 2024-06-15
Hi @jt14den, please hit ‘accept suggestion’ (and not ‘resolve’) for all suggestions you are happy to be incorporated into the final blog post. Most suggestions are changes from American to UK English spelling as per Carpentries style guide.

2024-06-27 01:35 UTC, jt14den commented
@OscarSiba think this is good to go, but some deploy tests failed.

2024-06-27 08:25 UTC, OscarSiba commented
> @OscarSiba think this is good to go, but some deploy tests failed.

Thank you @jt14den. Yes, there's been some problems with Netlify workflows for some time now, but all looks ok so we will merge.

2024-06-27 08:25 UTC, merged