Announcing LC Intro to Computational Thinking.
carpentries/carpentries.org-archive pull request #1860
Opened 2024-09-20 01:31 UTC by jt14den

A new lesson in Library Carpentry about computational thinking.

2024-10-14 10:55 UTC, maneesha commented
@OscarSiba This PR has been sitting for a few weeks. Does it need more work or review?

2024-10-16 12:46 UTC, OscarSiba requested changes
Hi there. Please find my recommended changes to the blog post. Please note also the recommended date of publication (21 October), but please do let me know if you wish to adjust this.

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +title: "Library Carpentry Curriculum Advisory Committee Announces Introduction of Computational Thinking"
```suggestion
title: "Library Carpentry Curriculum Advisory Committee Announces New Lesson: Introducing Computational Thinking"  
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +date: 2024-09-30
```suggestion
date: 2024-10-21  
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +The idea for [this lesson](http://librarycarpentry.org/lc-computational-thinking/) came from the author’s own experiences of teaching Software Carpentry lessons and learning to code. While Software C
```suggestion
The idea for the [Introducing Computational Thinking](http://librarycarpentry.org/lc-computational-thinking/) lesson came from my own experiences of teaching Software Carpentry lessons and learning to code. While Software Carpentry taught the fundamentals of task automation and coding, it did not directly address how to break problems down or how to apply a coding mindset to research questions. As a result, when I tried to apply what I had learned, I found it challenging to break problems down into computable chunks. I therefore saw a lesson on computational thinking as a necessary precursor to learning how to code.
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +The [Computational Thinking](http://librarycarpentry.org/lc-computational-thinking/)lesson is a pen-and-paper exercise that introduces people to the four steps of computational thinking. It explains
```suggestion
The [Introducing Computational Thinking](http://librarycarpentry.org/lc-computational-thinking/)lesson is a pen-and-paper exercise that introduces people to the four steps of computational thinking. It explains each step, provides examples, and covers tools for problem breakdown, including the use of pseudocode. Test exercises and problems are available for participants to work on individually or in groups. No prior knowledge of coding or computational thinking is required.
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +The [Computational Thinking lesson](http://librarycarpentry.org/lc-computational-thinking/) lesson introduces the building blocks of computational thinking, provides examples and exercises, and expla
```suggestion
The lesson introduces the building blocks of computational thinking, provides examples and exercises, and explains the use of pseudocode as a precursor to coding.
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +I couldn’t find a step-by-step course on computational thinking, so I decided to create one myself, which led to the development of [this lesson](http://librarycarpentry.org/lc-computational-thinking
```suggestion
I couldn’t find a step-by-step course on computational thinking, so I decided to create one myself, which led to the development of this lesson.
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +## Course Development
```suggestion
## Course development
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +The curriculum advisors adopted this lesson because it fills a critical gap in research skills training—specifically, the ability to break down complex problems into manageable chunks. Computational
```suggestion
The curriculum advisors adopted this lesson because it fills a critical gap in research skills training—specifically, the ability to break down complex problems into manageable chunks. Computational thinking is essential for librarians and information professionals serving disciplines where research is computationally produced. The [Introducing Computational Thinking](http://librarycarpentry.org/lc-computational-thinking/) lesson provides a practical framework for developing these skills and offers a starting point for Library Carpentry workshops that include hands-on coding lessons, such as the Unix Shell, Git, Python, and R.
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +We invite Carpentries instructors to teach the new [Computational Thinking lesson](http://librarycarpentry.org/lc-computational-thinking/) and provide feedback via the [repository Issues page](https:
```suggestion
We invite Carpentries Instructors to teach the new lesson and provide feedback via the [repository Issues page](https://github.com/LibraryCarpentry/lc-computational-thinking/issues) or by [reaching out to the Maintainers](https://carpentries.topicbox.com/groups/curriculum-advisors-lc).
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +## Course Author Biography
```suggestion
## Course author biography
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +This lesson serves as a precursor to coding but is also useful for anyone dealing with complex problems. Although this lesson was my own brainchild, all such lessons benefit from community involvemen
```suggestion
This lesson serves as a precursor to coding but is also useful for anyone dealing with complex problems. Although this lesson was my own brainchild, all such lessons benefit from community involvement. I encourage users to engage with the lesson and provide feedback for future improvements.
```

2024-10-16 12:46 UTC, OscarSiba commented on _posts/2024/09/2024-09-30-announcing-intro-computational-thinking
> +tags: ["Computational thinking", "Problem breakdown", "Structure diagrams"]
```suggestion
tags: ["Lessons", "Library Carpentry"]
```

2024-10-23 11:53 UTC, OscarSiba approved these changes

2024-10-23 11:54 UTC, merged