2024-10-17-Thank-you-Glosario
carpentries/carpentries.org-archive pull request #1863
Opened 2024-10-14 08:52 UTC by elletjies

2024-10-16 10:39 UTC, froggleston requested changes

2024-10-16 10:39 UTC, froggleston commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +We would like to extend our heartfelt thanks to everyone who **[contributed](https://github.com/carpentries/glosario/graphs/contributors)** in the Glosario Codefest, an event that highlighted the imp
The last sentence here is probably not required as it's the title of the blog and the text is repeated earlier in the paragraph.

2024-10-16 10:39 UTC, froggleston commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> + The Glosario site has been revamped, giving it a fresh look with modern fonts and a consistent design thanks to a Bootstrap library. Navigating through language pages is now easier, with categories
I'd remove "thanks to a Bootstrap library". This should also mention the fixes to the alphanumeric ordering.

2024-10-16 10:39 UTC, froggleston commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +### Enhanced Lesson Integration
This isn't actually in sandpaper yet as it will need some testing and documentation first.

2024-10-16 10:39 UTC, froggleston commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +We invite you to be part of this exciting initiative! If you are passionate about data science, programming, and making knowledge accessible to all, we encourage you to join us for future **[Glosario
"through the Glosario" should read "through Glosario".

2024-10-17 09:46 UTC, OscarSiba requested changes
Hi @elletjies. Please find review and let me know if you have any questions.

2024-10-17 09:46 UTC, OscarSiba commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +We would like to extend our heartfelt thanks to everyone who **[contributed](https://github.com/carpentries/glosario/graphs/contributors)** in the Glosario Codefest, an event that highlighted the imp
```suggestion
We would like to extend our heartfelt thanks to everyone who **[contributed](https://github.com/carpentries/glosario/graphs/contributors)** in the Glosario Codefest, an event that highlighted the importance of breaking down language barriers in data science and programming. Your contributions have helped create a more inclusive learning environment, advancing our vision of accessibility for the global community. This event, [supported by a grant from the Andrew W. Mellon Foundation](https://carpentries.org/blog/2024/01/mellon-foundation/), reflects a significant step forward in making data science knowledge available to all.
```

2024-10-17 09:46 UTC, OscarSiba commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +We would like to extend our heartfelt thanks to everyone who **[contributed](https://github.com/carpentries/glosario/graphs/contributors)** in the Glosario Codefest, an event that highlighted the imp
```suggestion
We would like to extend our heartfelt thanks to **[everyone who contributed](https://github.com/carpentries/glosario/graphs/contributors)** in the Glosario Codefest, an event that highlighted the importance of breaking down language barriers in data science and programming. Your contributions have helped create a more inclusive learning environment, advancing our vision of accessibility for the global community. This event, supported by a grant from the [Andrew W. Mellon Foundation](https://carpentries.org/blog/2024/01/mellon-foundation/), reflects a significant step forward in making data science knowledge available to all.
```

2024-10-17 09:46 UTC, OscarSiba commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +The Carpentries will host a Glosario Hackathon on 13 November 2024 during CarpentryConnect Heidelberg. The event is be hosted by [**The Bio Network for Training (BioNT) consortium](https://biont-trai
```suggestion
The Carpentries will host a Glosario Hackathon on 13 November 2024 during CarpentryConnect Heidelberg (CCHD2024). The event is be hosted by **[The Bio Network for Training (BioNT) consortium](https://biont-training.eu/)** with all its international partners and in collaboration with The Carpentries and their community members. CCHD2024 will run parallel to the BioNT community event, fostering collaboration and networking opportunities. 
```

2024-10-17 09:46 UTC, OscarSiba commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +This event encourages new contributions to Glosario from our governance and global community. This co-working session is a continuation of the work during the Glosario CodeFest 2024.The next session
```suggestion
This event encourages new contributions to Glosario from our governance and global community. This co-working session is a continuation of the work during the Glosario CodeFest 2024.The next session will be on **[6 November 2024 @ 15:00 UTC](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MTZubWQwZ2s0Ym81MXVjM25lZDFnZGk3YXJfMjAyNDExMDZUMTUwMDAwWiBvc2V1dW9odDB0dmpib2tnZzNub2g4YzQ3Z0Bn&tmsrc=oseuuoht0tvjbokgg3noh8c47g%40group.calendar.google.com&scp=ALL)**. You can [sign up on this Etherpad](https://pad.carpentries.org/Glosario_Codefest_2024) to attend. 
```

2024-10-17 09:46 UTC, OscarSiba commented on _posts/2024/10/2024-10-17-Thank-you-Glosario.md
> +We invite you to be part of this exciting initiative! If you are passionate about data science, programming, and making knowledge accessible to all, we encourage you to join us for future **[Glosario
```suggestion
We invite you to be part of this exciting initiative! If you are passionate about data science, programming, and making knowledge accessible to all, we encourage you to join us for future **[Glosario co-working sessions](https://carpentries.org/community/#community-events)**. Whether you want to learn more about Glosario or contribute to this event, we’d love to hear from you at **[community@carpentries.org(mailto:community@carpentries.org)]**. Your participation is key to shaping the future of inclusive data science education. Together, let’s celebrate diversity, break down language barriers, and empower learners worldwide through Glosario!
```

2024-10-17 13:22 UTC, OscarSiba approved these changes

2024-10-17 13:53 UTC, froggleston approved these changes

2024-10-17 15:14 UTC, merged