Create LatinTTT.md
carpentries/carpentries.org-archive pull request #207
Opened 2018-08-25 03:05 UTC by raynamharris

I'd like to submit this blog post. it was requested by @rgaiacs

2018-08-26 08:42 UTC, rgaiacs requested changes
Very inspirational blog post.

The only comment that you **must** address is the broken link at the end. All the others are suggestions that you might want to ignore to preserve your writing style.

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +teaser: ""
Can we use "Our most diverse Instructor Training so far"?

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +This month I co-taught an awesome Carpentry Instructor Training Workshop for 25 Spanish-speaking trainees in 6 countries in Latin America. One thing that made this workshop so special for me is that
Replace

> an awesome Carpentry Instructor Training Workshop

with

> an awesome The Carpentries Instructor Training Workshop

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +This month I co-taught an awesome Carpentry Instructor Training Workshop for 25 Spanish-speaking trainees in 6 countries in Latin America. One thing that made this workshop so special for me is that
Can we also add "remote"?

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +### The early days of Spanish Carpentry workshops
Replace

> The early days of Spanish Carpentry workshops

with

> The early days of The Carpentries workshops in Spanish

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +### The early days of Spanish Carpentry workshops
When I read "Spanish * workshop" I first think of Spain but when I read "workshop in Spanish" it is clear to me that you are talking about the language so the workshop could have happened in Spain or Argentina or Mexico or ...?

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +In 2016, Greg Wilson introduced to Selene Fernandez-Valverde to discuss a Software Carpentry meets Spanish-speaking bioinformatics endeavour. Back then my Spanish was 8 years out of practice and I wa
In "introduced to" do we need the "to"? It sounds weird to me.

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +In 2016, Greg Wilson introduced to Selene Fernandez-Valverde to discuss a Software Carpentry meets Spanish-speaking bioinformatics endeavour. Back then my Spanish was 8 years out of practice and I wa
Replace

> This observation led to two simultaneous efforts to 1) support a community-wide effort for collaborative lesson translation, and 2) provide instructor training for Spanish speaking instructors.

> This observation led to two simultaneous efforts: support a community-wide effort for collaborative lesson translation and provide instructor training for Spanish speaking instructors.

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +In December 2017, I finished my PhD, and I decided to go visit all the awesome open-science advocates that I met at OpenCon in Buenos Aires. I met Juli Aranco from Buenos Aires and we organized a one
Can you include links to the Git and R lesson? Specially because we have more than one R lesson?

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +The real momemtum for me for instructor training came from being introduced to the [R Ladies Buenos Aires](https://www.meetup.com/rladies-buenos-aires/) community in February 2018. One of my co-instr
Replace

>  Spanish Carpentry workshop

with

>  The Carpentries workshop in Spanish

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +Finally, in August 2018 we make it to the thing that people have been waiting for, a [fully distributed online instructor training](https://twitter.com/raynamharris/status/1030828857929224192) with p
Do we have a broke link here? See `[1]`.

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +Finally, in August 2018 we make it to the thing that people have been waiting for, a [fully distributed online instructor training](https://twitter.com/raynamharris/status/1030828857929224192) with p
Can we have the link to the episode in Spanish and in English?

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +Finally, in August 2018 we make it to the thing that people have been waiting for, a [fully distributed online instructor training](https://twitter.com/raynamharris/status/1030828857929224192) with p
Also, could you add Ajejandra's surname?

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +Finally, in August 2018 we make it to the thing that people have been waiting for, a [fully distributed online instructor training](https://twitter.com/raynamharris/status/1030828857929224192) with p
Replace

> The Carpentry [teaching practices]

with

> The Carpentries [teaching practices]

2018-08-26 08:42 UTC, rgaiacs commented on _posts/2018/08/LatinTTT.md
> +As with the lesson translations, everyone is enthusiastic about organizing more workshops and expanding the curricula. These will be a long-term community project. To get involved, check out our [Git
```
join the [Carpentries Latin America mailing list](email list for the Latin America group is https://carpentries.topicbox.com/groups/local-latinoamerica).
```

has a broken link. Please replace with

```
join the [Carpentries Latin America mailing list](https://carpentries.topicbox.com/groups/local-latinoamerica).
```

2018-08-26 18:38 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +teaser: ""
Hmm. Anelda might have me beat there on diversity. How about "Building global communities of Spanish-speaking Carpentry instructors and lesson developers."

2018-08-26 18:38 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +This month I co-taught an awesome Carpentry Instructor Training Workshop for 25 Spanish-speaking trainees in 6 countries in Latin America. One thing that made this workshop so special for me is that
done. done.

2018-08-26 18:39 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +### The early days of Spanish Carpentry workshops
very good point. corrected.

2018-08-26 18:41 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +In 2016, Greg Wilson introduced to Selene Fernandez-Valverde to discuss a Software Carpentry meets Spanish-speaking bioinformatics endeavour. Back then my Spanish was 8 years out of practice and I wa
changed to "introduced _me_ to".

Replace. And elaborated :)

2018-08-26 18:43 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +In December 2017, I finished my PhD, and I decided to go visit all the awesome open-science advocates that I met at OpenCon in Buenos Aires. I met Juli Aranco from Buenos Aires and we organized a one
done

2018-08-26 18:45 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +The real momemtum for me for instructor training came from being introduced to the [R Ladies Buenos Aires](https://www.meetup.com/rladies-buenos-aires/) community in February 2018. One of my co-instr
done. link added

2018-08-26 19:24 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +Finally, in August 2018 we make it to the thing that people have been waiting for, a [fully distributed online instructor training](https://twitter.com/raynamharris/status/1030828857929224192) with p
- no missing [1]. I almost added a footnote but i changed my mind.
- done
- done
- done

2018-08-26 19:25 UTC, raynamharris commented on _posts/2018/08/LatinTTT.md
> +As with the lesson translations, everyone is enthusiastic about organizing more workshops and expanding the curricula. These will be a long-term community project. To get involved, check out our [Git
done

2018-08-26 19:26 UTC, raynamharris commented
Okay, I think this is ready to merge. Link fixed. Comments incoporated

2018-08-27 00:37 UTC, weaverbel commented
Constant Travis CI build errors so I created a new file and it has merged fine. https://carpentries.org/blog/2018/08/latin-ttt/ Closing this PR as a result.

2018-08-27 00:37 UTC, closed without merging

2018-08-27 04:53 UTC, raynamharris commented
Thanks @weaverbel !