Create 2019-01-17-python-ecology-es.md
carpentries/carpentries.org-archive pull request #349
Opened 2019-01-16 00:08 UTC by raynamharris

a blog post about translating the Data Ecology Python lesson. Please wait for approval from co-authors and some people mention. I'll post a message when its okay to merge. Thanks!

2019-01-16 00:41 UTC, charlesreid1 reviewed
See comment re fixing the Travis build problem

2019-01-16 00:41 UTC, charlesreid1 commented on _posts/2019/01/2019-01-17-python-ecology-es.md
> +From September 2017 to May 2018, there was [community-driven effort](https://software-carpentry.org/blog/2018/03/forlatinamerica.html) to translate the Software Carpentry lessons into Spanish, and th
should read "the production **of** three high-quality"

2019-01-16 00:41 UTC, charlesreid1 commented on _posts/2019/01/2019-01-17-python-ecology-es.md
> +tags: ["Translation", "Latin America" "Lessons", "Data Carpentry", "Community"]
If you remove the double quotes, and change this to just `tags: [Translation, Latin America, Lessons, Data Carpentry, Community]`, the Travis CI build problem should be fixed.

2019-01-16 14:42 UTC, ComplejoC requested changes
Saludos! Pudieran añadir mi segundo apellido? Mi nombre completo es Sofía Meléndez Cartagena

2019-01-16 15:01 UTC, NPalopoli commented on _posts/2019/01/2019-01-17-python-ecology-es.md
> +From September 2017 to May 2018, there was [community-driven effort](https://software-carpentry.org/blog/2018/03/forlatinamerica.html) to translate the Software Carpentry lessons into Spanish, and th
And line 11 is missing "a" in "there was a community-driven effort"

2019-01-16 21:02 UTC, raynamharris commented on _posts/2019/01/2019-01-17-python-ecology-es.md
> +tags: ["Translation", "Latin America" "Lessons", "Data Carpentry", "Community"]
thank you! I've been wondering what was wrong.

2019-01-16 21:04 UTC, raynamharris commented on _posts/2019/01/2019-01-17-python-ecology-es.md
> +tags: ["Translation", "Latin America" "Lessons", "Data Carpentry", "Community"]
done! https://github.com/carpentries/carpentries.org/pull/349/commits/9d010ccd4b425c73eeb7c9c9de1e6f44bc65f956

2019-01-16 21:05 UTC, raynamharris commented on _posts/2019/01/2019-01-17-python-ecology-es.md
> +From September 2017 to May 2018, there was [community-driven effort](https://software-carpentry.org/blog/2018/03/forlatinamerica.html) to translate the Software Carpentry lessons into Spanish, and th
Thanks! missing words added with https://github.com/carpentries/carpentries.org/pull/349/commits/c3e9dfe4376e79ce2ca47992544834ac3cd76bda

2019-01-16 21:08 UTC, raynamharris commented
Gracias @ComplejoC! Agregué tu apellido https://github.com/carpentries/carpentries.org/pull/349/commits/80e604529fd6cd7c56f1fb94d17991dd524eb146

2019-01-17 14:53 UTC, raynamharris commented
Ready to post @fmichonneau

2019-01-17 20:21 UTC, merged

2019-01-17 20:21 UTC, fmichonneau commented
Thanks!