add 2019 EC
carpentries/carpentries.org-archive pull request #357
Opened 2019-01-28 01:40 UTC by raynamharris

2019-01-28 14:51 UTC, fmichonneau requested changes
Edits based on https://carpentries.org/blog/2018/12/ec-election-results/

2019-01-28 14:51 UTC, fmichonneau commented on pages/governance.md
> +- Mesfin Diro Chaka (elected in 2019)
appointed in 2019

2019-01-28 14:51 UTC, fmichonneau commented on pages/governance.md
> +- Amy Hodge (elected in 2018)
(re-)elected in 2019

2019-01-28 14:51 UTC, fmichonneau commented on pages/governance.md
> +- Joslynn Lee (elected in 2019)
appointed in 2019

2019-01-28 14:51 UTC, fmichonneau commented on pages/governance.md
> +- Juan Steyn (elected in 2019)
appointed in 2019

2019-01-28 14:51 UTC, fmichonneau commented on pages/governance.md
> +- Elizabeth Wickes (elected in 2018)
(re-)elected in 2019

2019-01-29 18:23 UTC, merged

2019-01-29 18:23 UTC, kariljordan commented
I reviewed and merged these changes. Thank you @fmichonneau for the fixes!