add strategic plan to the website
carpentries/carpentries.org-archive pull request #670
Opened 2020-01-29 09:23 UTC by serahrono

2020-01-29 10:42 UTC, lexnederbragt requested changes
Looks good. I propose some, hopefully minor, changes.

2020-01-29 10:42 UTC, lexnederbragt commented on pages/about.md
> +[The Carpentries Strategic Plan](https://carpentries.org/strategic-plan) was developed by the Core Team and approved by the Executive Council in January 2020.
```suggestion
[The Carpentries Strategic Plan](https://carpentries.org/strategic-plan) was developed by the Executive Council together with the Core Team and approved by the Executive Council in January 2020.
```

2020-01-29 10:42 UTC, lexnederbragt commented on pages/about.md
> +[The Carpentries Strategic Plan](https://carpentries.org/strategic-plan) was developed by the Core Team and approved by the Executive Council in January 2020.
The core team was involved in the process, but I hope you agree that development of the strategic plan is a task of the Executive Council...

2020-01-29 10:42 UTC, lexnederbragt commented on pages/strategic-plan.md
> +This Strategic Plan describes how the Executive Council and [The Carpentries Core Team](https://carpentries.org/team/) see the path forward toward that future. It lays out six broad goals, each with
```suggestion
This Strategic Plan describes how the [Executive Council](https://static.carpentries.org/governance/) and [The Carpentries Core Team](https://carpentries.org/team/) see the path forward toward that future. It lays out six broad goals, each with its rationale and underlying objectives, that will serve as touchpoints to guide our future actions. The idea is to provide a general framework for the direction of this organisation for the next 3-5 years. This Strategic Plan speaks to The Carpentries as a whole. Each of the individual Lesson Programs -- Data Carpentry, Library Carpentry, and Software Carpentry -- may also have their own goals and objectives related to their specific programs and curricula.
```

2020-01-29 10:42 UTC, lexnederbragt commented on pages/strategic-plan.md
> +This Strategic Plan describes how the Executive Council and [The Carpentries Core Team](https://carpentries.org/team/) see the path forward toward that future. It lays out six broad goals, each with
(add link to EC)

2020-01-29 10:42 UTC, lexnederbragt commented on pages/strategic-plan.md
> +title: "Our Strategic Plan"
```suggestion
title: "Our Strategic Plan for 2020-2025"
```

2020-01-29 11:54 UTC, kariljordan commented
Thanks @serahrono for having this added to the website so quickly. I've looked at the strategic plans on a few non-profit websites and some have contact information. Thoughts on including that?

2020-01-29 12:07 UTC, serahrono commented
thanks for reviewing and adding edits @lexnederbragt 👍 

@kariljordan, sure thing, what email can the executive council be reached on?

2020-01-29 12:35 UTC, lexnederbragt commented
That would be carpentries-executive-council@carpentries.org (the address 'anyone can send to').

2020-01-29 15:05 UTC, amyehodge commented on pages/about.md
> +[The Carpentries Strategic Plan](https://carpentries.org/strategic-plan) was developed by the Core Team and approved by the Executive Council in January 2020.
I like this rewording. This was a project initiated and completed by the EC with major contributions from the Core Team, without which this would not have been completed. I think this rewording reflects that fairly well without getting into the weeds of the process.

2020-01-30 12:59 UTC, serahrono commented
ok, team -

 looks like we are all set, and ready to share the Strategic Plan with the community! I appreciate the timeliness and thoughtfulness with which you've approached this process, and feel very excited to have this go out today. 
Thank you, @lexnederbragt, @kariljordan,  @amyehodge and the Executive Council! ![Badge_Carpentries_icon](https://user-images.githubusercontent.com/4550385/73451766-0a378e80-4371-11ea-8f65-0fc038ec948b.png)

2020-01-30 13:47 UTC, merged