provide recommendation for migration to R 4.0
carpentries/carpentries.org-archive pull request #830
Opened 2020-07-24 21:57 UTC by zkamvar

Derived from conversations in the June maintainer meeting. 

cc @jcoliver @HaoZeke

2020-07-24 23:14 UTC, HaoZeke commented
Looks great to me. Thanks for setting this up!

2020-07-24 23:14 UTC, HaoZeke approved these changes

2020-07-31 21:47 UTC, naupaka reviewed
Small typo.

2020-07-31 21:47 UTC, naupaka commented on _posts/2020/08/2020-08-03-r-4-migration.md
> +This is a draft of ideas for our migration of the R lessons to use version 5.0 and recommendations for future migrations. The idea is for us to hash out our ideas for the migration on this document a
4.0, right?

2020-07-31 23:06 UTC, zkamvar commented on _posts/2020/08/2020-08-03-r-4-migration.md
> +This is a draft of ideas for our migration of the R lessons to use version 5.0 and recommendations for future migrations. The idea is for us to hash out our ideas for the migration on this document a
Yes! :facepalm: 

Luckily it's in the comments, so I'll just remove them. Thanks for pointing that out! :sweat_smile:

2020-08-01 02:47 UTC, HaoZeke approved these changes
Excellent ^_^

2020-08-03 21:01 UTC, atheobold requested changes
I've made changes to the history of factors and suggestions for ways maintainers can more meaningfully introduce them in their lessons.

2020-08-03 21:01 UTC, atheobold commented on _posts/2020/08/2020-08-03-r-4-migration.md
> +Now that characters are no longer converted to factors by default, for lessons that previously used the default parameters as an introduction, there is an extra step needed to introduce the concept,
```suggestion
Now that characters are no longer converted to factors by default, for lessons that previously used the default parameters as an introduction, we can reinvigorate our lessons to provide more meaningful introductions to factors. 
**Maintainers of the lessons will need to evaluate the underlying structure of the lessons to determine how to meaningfully introduce factors.** Maintainers of lessons that are affected by this change in the default behavior might find motivations for the usefulness of factors in data wrangling and data visualization tasks. For example, when summarizing variables, the author may wish for a table of character data to have a specific ordering. Alternatively, when visualizing how a relationship changes over time, it may be inappropriate for time to be considered as continuous. Additionally, maintainers can reference the [section on factors from the *R for Social Science* lesson](https://datacarpentry.org/r-socialsci/02-starting-with-data/index.html#factors), which was unaffected by the changes.  
```

2020-08-03 21:01 UTC, atheobold commented on _posts/2020/08/2020-08-03-r-4-migration.md
> +Several lessons use the former (i.e. < 4.0) default setting of `stringsAsFactors = TRUE` to introduce the learner to the concept of factors.  Factors themselves are a bit of a weird concept in R: lar
```suggestion
Several lessons use the former (i.e. < 4.0) default setting of `stringsAsFactors = TRUE` to introduce the learner to the concept of factors.  Factors themselves are a bit of a weird concept in R, their importance dates back to when R users had to worry about the storage space of their computer. Given that today's netbook has no problem working with character data, our lessons should provide more meaningful introductions to the usefulness of factors. 

In previous versions of R, factors were often one of the first data structures people see when reading data into R. Thus, it made sense to teach these concepts to novice R users, which follows the concept of teaching [immediately useful content first](https://cdh.carpentries.org/deciding-what-to-teach.html). 
```

2020-08-03 21:22 UTC, zkamvar commented
Thank you for your input @atheobold! This definitely improves the tone of the post and gives valuable information. Would you mind adding your name to the Author list? https://github.com/carpentries/carpentries.org/pull/830/files#diff-97b5acc7d7fc4a2fc596284eee1ad44dR3

This post will go live tomorrow at 1400 UTC.

2020-08-03 22:01 UTC, atheobold commented on _posts/2020/08/2020-08-03-r-4-migration.md
> +authors: ["Rohit Goswami", "Zhian N. Kamvar", "Jeff Oliver"]
```suggestion
authors: ["Rohit Goswami", "Zhian N. Kamvar", "Jeff Oliver", "Allison Theobold"]
```

2020-08-04 16:41 UTC, merged