Add blog post Traduciendo
carpentries/carpentries.org-archive pull request #834
Opened 2020-08-04 03:42 UTC by orchid00

Here tagging co-author for a last check
@flor14 @dpshelio Aprueben los cambios por favor, creo q esta listo para ser posteado.

Paula

2020-08-04 13:33 UTC, dpshelio requested changes
Unas sugerencias pequeñitas :wink:

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +## ¿Y tú como traducirías esta palabra?
```suggestion
## ¿Y tú cómo traducirías esta palabra? 
```
Pero no te creas que estaba al 100% seguro ;) - aquí [me tienes aprendiendo todos los significados de cómo-como](https://github.com/carpentries/carpentries.org/pull/834) :joy:

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +### CarpentryCon@HOME traduciendo
```suggestion
### CarpentryCon@HOME traduciendo

```
Por claridad cuando se vea el archivo en md.

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +### Protagonistas
```suggestion
### Protagonistas

```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +### Pasos a seguir
```suggestion
### Pasos a seguir

```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +### Otras sesiones relacionadas
```suggestion
### Otras sesiones relacionadas

```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +(agregar la foto aquí).
¿qué foto queremos añadir?

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira,  Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, J
```suggestion
David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira,  Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, Juanjo Garcia Mesa, Maggie Suero, Yanina Bellini Saibene, Paula Videla, Virginia A. García Alonso, Monica Alonso, Raquel, Rayna Harris.
```
Faltaban las que empiezan por R :joy:, y eso que era una lección de R :stuck_out_tongue_closed_eyes:

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +**Los esperamos el 10 de Agosto, 2020** para el sprint parte 2 [https://pad.carpentries.org/cchome-sprint-traduciendo](https://pad.carpentries.org/cchome-sprint-traduciendo).
```suggestion
**Les esperamos el 10 de Agosto, 2020** para el sprint parte 2 ([pad de la sesión](https://pad.carpentries.org/cchome-sprint-traduciendo)).
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +![](https://i.imgur.com/kpsyuSV.jpg)
Probablemente sea mejor añadir la foto (el archivo) aquí, así no se pierde del blog.
```suggestion
![Cara de emoción de los participantes en el momento que los tres anfitriones estaban presente](https://i.imgur.com/kpsyuSV.jpg)
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +* Visualización y programación con Python (gapminder) - SWC en revisión final antes de ser publicada
Mejor con los enlaces, no creen?
```suggestion
* [Control de versiones con Git](http://swcarpentry.github.io/git-novice-es) - SWC
* [La Terminal de Unix](http://swcarpentry.github.io/shell-novice-es) - SWC
* [R para Análisis Científicos Reproducibles (gapminder)](http://swcarpentry.github.io/r-novice-gapminder-es) - SWC
* [Análisis y visualización de datos usando Python](https://datacarpentry.org/python-ecology-lesson-es/) - DC
* [Visualización y programación con Python (gapminder)](https://carpentries-i18n.github.io/python-novice-gapminder/es/) - SWC en revisión final antes de ser publicada
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +Es la motivación de personas en Latinoamerica y expats a abrir las puertas para que más personas hispanohablantes acedan el valioso material de enseñanza de las carpentries es reflejado en los varios
```suggestion
La motivación de personas en Latinoamérica y expats a abrir las puertas para que más personas hispanohablantes accedan al valioso material de enseñanza de las Carpentries está reflejado en los varios talleres que se han organizado en la región desde el 2014:
```
La palabra "expats" nunca la he oído en español.

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +[https://github.com/Carpentries-ES/board/blob/master/talleres.md](https://github.com/Carpentries-ES/board/blob/master/talleres.md)
No es una buena práctica el poner el enlace en "plano". En vez de poner los `:` de arriba, mejor decir:
```
[en los varios talleres que se han organizado en la región desde el 2014](https://github.com/Carpentries-ES/board/blob/master/talleres.md).
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +![](https://i.imgur.com/8WKyxIL.png)
La imágen necesita un texto para ayudar a la accesibilidad, y creo que mejor la imágen se guarde en el blog. Hay una carpeta en: `images/blog/2020/07/`

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira, Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, Ju
Faltan los nombres de arriba.
```suggestion
David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira, Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, Juanjo Garcia Mesa, Maggie Suero, Yanina Bellini Saibene, Paula Videla, Virginia A. García Alonso, Monica Alonso, Raquel, Rayna Harris.
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +**We wait for you on 10th of August, 2020 to continue the translation sprint part 2** [https://pad.carpentries.org/cchome-sprint-traduciendo](https://pad.carpentries.org/cchome-sprint-traduciendo).
```suggestion
**We wait for you on the 10th of August, 2020 to continue the translation sprint part 2** ([pad for the session](https://pad.carpentries.org/cchome-sprint-traduciendo)).
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +![](https://i.imgur.com/kpsyuSV.jpg)
```suggestion
![Excited face of the participants when the three hosts were present](https://i.imgur.com/kpsyuSV.jpg)
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +![](https://i.imgur.com/kpsyuSV.jpg)
Y actualizar el enlace una vez la imagen esté en el repositorio.

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +* Datos espaciales con R - DC  ( needs final revision before being published)
```suggestion
* [Version control with Git](http://swcarpentry.github.io/git-novice-es) - SWC
* [Unix Terminal](http://swcarpentry.github.io/shell-novice-es) - SWC
* [R for Reproducible Scientific Analysis (gapminder)](http://swcarpentry.github.io/r-novice-gapminder-es) - SWC
* [Analysis and visualization of data using Python](https://datacarpentry.org/python-ecology-lesson-es/) - DC
* [Visualization and programming with Python (gapminder)](https://carpentries-i18n.github.io/python-novice-gapminder/es/) - SWC (needs final revision before being published)
* [Datos espaciales con R](https://carpentries-i18n.github.io/r-intro-geospatial/) - DC  (needs final revision before being published)
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +[https://github.com/Carpentries-ES/board/blob/master/talleres.md](https://github.com/Carpentries-ES/board/blob/master/talleres.md)
```suggestion
In addition, the motivation of people in Latin America and expats to open the doors so that more Spanish-speaking people access the valuable teaching material of the carpentries is reflected in [the various workshops that have been organised in the region since 2014](https://github.com/Carpentries-ES/board/blob/master/talleres.md).
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +Inside the CarpentryCon there will also be a session on [the machinery that combines the lessons into fragments that can then be used in Transifex](https://2020.carpentrycon.org/schedule/#session-22)
```suggestion
At the CarpentryCon there will also be a session on [the machinery that combines the lessons into fragments that can then be used in Transifex](https://2020.carpentrycon.org/schedule/#session-22). This session will be in English and is aimed at those who want to help make the process easier for everyone and start new communities of translation into other languages.
```

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +![](https://i.imgur.com/8WKyxIL.png)
Descripción de la imagen y actualizar enlace a la imagen local.

2020-08-04 13:33 UTC, dpshelio commented on _posts/2020/08/2020-08-04-Hablamos.md
> +tags: ["Carpentries Lessons","Infrastructure", "community", "Latam", "Latinoamerica", "Español"]
```suggestion
tags: ["Carpentries Lessons", "Infrastructure", "Community", "Latin America", "Spanish", "Internationalisation"]
```
Looking at the tags available [within the Blog](https://carpentries.org/posts-by-tags/)

2020-08-04 14:32 UTC, serahrono commented
Hi @orchid00, as you work on this post, do you know when you would like it to go out by?

2020-08-05 10:28 UTC, orchid00 commented on _posts/2020/08/2020-08-04-Hablamos.md
> +* Datos espaciales con R - DC  ( needs final revision before being published)
Eso esta muy bueno! agregar los links

2020-08-05 10:44 UTC, orchid00 reviewed
alol comments addressed

2020-08-05 10:44 UTC, orchid00 commented on _posts/2020/08/2020-08-04-Hablamos.md
> +Junto con David, Paula y Florencia compartimos toda la sesión, permitiendo unirse a gente de todo el mundo en la franja horaria que fuese más conveniente para ellos.
```suggestion
Entre David, Paula y Florencia compartimos toda la sesión, permitiendo unirse a gente de todo el mundo en la franja horaria que fuese más conveniente para ellos.
```

2020-08-05 10:44 UTC, orchid00 commented on _posts/2020/08/2020-08-04-Hablamos.md
> +David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira,  Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, J
```suggestion
David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira,  Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, Juanjo Garcia Mesa, Maggie Suero, Yanina Bellini Saibene, Paula Videla, Virginia A. García, Monica Alonso, Raquel, Rayna Harris.
```

2020-08-05 10:44 UTC, orchid00 commented on _posts/2020/08/2020-08-04-Hablamos.md
> +David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira, Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, Ju
```suggestion
David Pérez-Suárez, Florencia D'Andrea, Paula Andrea Martinez, Verónica Jiménez Jacinto, Natalia Morandeira, Irma Martínez-Flores, Nicolás Guarín-Zapata, Silvia Rodríguez-Pires, Priscilla Minotti, Juanjo Garcia Mesa, Maggie Suero, Yanina Bellini Saibene, Paula Videla, Virginia A. García, Monica Alonso, Raquel, Rayna Harris.
```

2020-08-05 10:45 UTC, orchid00 commented
Hi @flor14 and @dpshelio gracias por los comments, i think I committed all the suggestions.
Except the photo url. 
@serahrono It is ready to merge. I converted it to a draft to fix the commits, does that still work to merge?

2020-08-05 12:41 UTC, serahrono commented
Hi @orchid00, it should work fine. We will publish it first thing on Monday morning cc @kmomar

2020-08-06 01:51 UTC, orchid00 commented
Hi @serahrono and @kmomar is there any possibility to do that sooner rather than on Monday? In the post we are inviting people to attend to the second translation sprint which will happen on Monday

2020-08-06 13:33 UTC, kmomar commented
@orchid00 Hello, Yes we can publish today if that works and it is ready.

2020-08-06 13:56 UTC, merged