[blog post] add post for lesson design principles
carpentries/carpentries.org-archive pull request #844
Opened 2020-08-10 05:44 UTC by fmichonneau

@zkamvar could you please do a final review?

@kmomar Could please post this sometime this week when it fits with the rest of the blog posting schedule?

2020-08-10 05:45 UTC, fmichonneau commented on _posts/2020/08/2020-08-10-lesson-template-design.md
> +2. Figures are stored separately from the content, and linking to them can be difficult.
@zkamvar could you please clarify this point? I'm not sure what you mean here.

2020-08-10 15:12 UTC, zkamvar commented on _posts/2020/08/2020-08-10-lesson-template-design.md
> +2. Figures are stored separately from the content, and linking to them can be difficult.
```suggestion
2. The folder structure was designed for programmers, not lesson developers, which caused a lot of confusion about how to access different elements in the hierarchy. This was further complicated when we introduced the ability to use RMarkdown to auto-generate the output and figures.
```

I think I generally wanted to address how people felt about the folder structure in our lessons.

2020-08-10 17:59 UTC, zkamvar requested changes
Thank you for putting this together, François! 

The design principles are clear and I think some improvements can be made on the background, specifically to connect the users to how they interact with different components of the templates. 

It may be out of scope, but I think we need to compare and contrast how the user types interact with the current lesson infrastructure and how the user types will interact with the new lesson infrastructure.

Here's how I envision it: 

1. define the components of our lesson infrastructure as a list
2. introduce our users and how the interact with the lesson template in text and image form
3. identify pain points
4. introduce the new way where only the template contributor interact with the template. 
5. list our lesson design principles

I'm going to make some changes in a single commit, so you can revert it if you wish. 

This is what I changed:

 - Terminology: changed "lesson template" to "styling elements". We
   interchangeably referred to the "lesson template" as the entire
   workflow and the styling elements. By calling the CSS, HTML
   templates, and JavaScript backend as "styling elements", it's easier
   to be clear what we are talking about
 - Arrangement: I've placed the tooling definitions at the beginning
   because they underly the rest of the post. I've also modified the
   figure slightly to give more room to the rendering tools and update
   the language.
 - Design principles: I've rearranged the design principles in
   Human-centered lesson template that goes from broad to specific
   ideas.

2020-08-10 17:59 UTC, zkamvar commented on _posts/2020/08/2020-08-10-lesson-template-design.md
> +![Drawing of the components that lead to rendered lesson. A rendered lesson is the output by a rendering tool of a lesson template and the lesson content]({{ site.urlimg }}/blog/2020/08/2020-08-10-le
Because this exists as an SVG, it renders differently on Firefox and Chrome. I think it may be worthwhile to redo this to show how the different personas interact with the different elements.

2020-08-10 18:49 UTC, zkamvar commented
Aaaand of course the build fails with no helpful error when I push a commit :slightly_frowning_face: https://app.netlify.com/sites/stupefied-einstein-5bde90/deploys/5f319611ed59ab0007a7ee72

2020-08-10 18:50 UTC, zkamvar commented on _posts/2020/08/2020-08-10-lesson-template-design.md
> +2. Figures are stored separately from the content, and linking to them can be difficult.
addressed in 4306de4

2020-08-11 08:20 UTC, fmichonneau commented
Thanks @zkamvar, these changes look good and make the post better.
@kmomar, this is ready to be published (please adjust the date before doing so).

2020-08-11 08:21 UTC, fmichonneau commented
> Aaaand of course the build fails with no helpful error when I push a commit slightly_frowning_face [app.netlify.com/sites/stupefied-einstein-5bde90/deploys/5f319611ed59ab0007a7ee72](https://app.netlify.com/sites/stupefied-einstein-5bde90/deploys/5f319611ed59ab0007a7ee72)

I think this was a fluke.

2020-08-11 13:55 UTC, kmomar commented
Hi @fmichonneau and @zkamvar. We will be publishing 12 August to allow for @serahrono to review the post.

2020-08-12 11:25 UTC, serahrono commented
this is a fantastic post, phenomenal work @zkamvar, @fmichonneau  and Erin 🙌 

@kmomar, I have reviewed and added some edits. Please do a final round of checks and merge when ready

2020-08-12 12:55 UTC, fmichonneau commented
Thanks Serah!

2020-08-12 12:55 UTC, merged